### ISSUE TITLE
Add images with using CTRL+V in messages and activity feed

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#1003]
**Is your feature request related to a problem? Please describe.**
It would be much more convenient if it were possible to add images and screenshots into messages and activity feed post directly from the clipboard with using CTRL+V hotkeys.

**Describe the solution you'd like**
Add images with using CTRL+V in messages and activity feed

**Describe alternatives you've considered**
Any popular social networks (and GitHub) and messengers can do it. 
[BP Better Messages](https://wordpress.org/plugins/bp-better-messages/) plugin can do it. 

- buddyboss-platform 1.4.1

**Comment by marienel21** [comment]
Hi @AiratHalitov,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
