### ISSUE TITLE
Document file protection issue

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1014]
**Describe the bug**
After uploading a file, with applying privacy settings, the file remains unprotected on the server. The file can still be accessed by visiting an Attachment page url for example. Also, the file name remains directly accessible when entering the url to the stored file in the Uploads folder

**To Reproduce**
1. Upload a document in your profile
2. Set the privacy setting to only me
3. Get the document URL in your backend
4. View the document in incognito mode
5. Notice that the document is viewable and downloadable by any user.

**Expected behavior**
The document should not be accessible by the users if the privacy is applied.

**Support ticket links**
https://secure.helpscout.net/conversation/1188681025/76837

**Comment by eisenwasser** [comment]
@furqanbb This is resolved for all newly added files ever since this release:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-1/

We will need to migrate previously uploaded files in a new release with a migration script. New ones should all be protected as the entire directory they are uploaded into is restricted. Even in the backend you cannot view the document.

**Comment by furqanbb** [comment]
Ok, thanks @eisenwasser
