### ISSUE TITLE
Force users to upload profile picture in register form (admin can control this feature)

### ISSUE THREAD

**Issue by makfoulie** [buddyboss/buddyboss-platform#1076]
**Is your feature request related to a problem? Please describe.**
Admin can set (yes or not) as mandatory the profile picture field in register form.

**Describe the solution you'd like**
Admin can add the profile picture field to appear on register form and select it as mandatory. No cropping, users just upload a profile picture when register.

**Describe alternatives you've considered**
none actually

**Support ticket links**
No ticket.

Hope you'll understand my poor english^^.

Regards.

**Comment by makfoulie** [comment]
Hello, any news about this feature ?

**Comment by marienel21** [comment]
Hi @makfoulie ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
