### ISSUE TITLE
BuddyCircles User Profile Integration

### ISSUE THREAD

**Issue by Coopman14** [buddyboss/buddyboss-platform#1119]
**Is your feature request related to a problem? Please describe.**
I would like users to be able to limit visibility of individual profile fields based on groups of Connections they determine.

**Describe the solution you'd like**
In the same way that users can limit profile field visibility to "public", "all members", "my connections", and "only me", offer a second menu for each profile field that allows them to select Circles of contacts created with the BuddyCircles plugin to further stipulate visibility to that profile field.

**Describe alternatives you've considered**
I considered several options, such as closed Groups or Forums.  None would have the functionality I am looking for.

**Support ticket links**
79712

**Comment by marienel21** [comment]
Hi @Coopman14 ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
