### ISSUE TITLE
AJAX

### ISSUE THREAD

**Issue by gaudigva** [buddyboss/buddyboss-platform#1135]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to have Buddyboss with AJAX navigation for all components compatible with Buddyboss theme like Buddypress, Learndash, Geodirectory ...

**Describe the solution you'd like**
To do like Facebook and new profesional websites

**Comment by marienel21** [comment]
Hi @gaudigva ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
