### ISSUE TITLE
Variable Display Name Format

### ISSUE THREAD

**Issue by proskurius** [buddyboss/buddyboss-platform#1162]
Hello. 
Can you add a possibility for users to change their "Display Name Format"? For example someone wants to display First Name and Last Name, but someone else wants to hide this information and display Nickname only.

**Comment by marienel21** [comment]
Hi @proskurius,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
