### ISSUE TITLE
Bug - conflict with "Invite Anyone" plugin

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#1172]
**Describe the bug**
The plugin "Invite Anyone" (https://www.buddyboss.com/resources/docs/integrations/buddypress-add-ons/invite-anyone/) breaks some of BuddyBoss's functionality...

During the Group Creation steps on the front end, the option to check the "Create and sync a LearnDash group" is not available any longer. (It is enabled in back-end and also works correctly when Invite-Anyone is disabled)

Also, the "Invite Anyone" email invite step in the Group Creation process completely replaces the email invite step of BuddyBoss Platform.

**To Reproduce**
1. Install plugin "Invite Anyone"
2. Enable Learndash/BuddyBoss group syncing
3. Try to create a group, see above errors

**Expected behavior**
Invite Anyone functionality should work as it does with BuddyPress.

**Screenshots**
None

**Support ticket links**
Reported by user @JPvanRooyen here:
https://github.com/buddyboss/buddyboss-platform/issues/685

**Jira issue** : [PROD-937]

[PROD-937]: https://buddyboss.atlassian.net/browse/PROD-937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by JPvanRooyen** [comment]
I can confirm that the BuddyBoss Invite step is still completely replaced by Invite Anyone's email invite step, meaning the code @ Invite Anyone takes precedence over BuddyBoss, instead of just adding a step.

Ideally, the email invites could be consolidated on the BuddyBoss invites step (I altered the template file to include a link to IA's email invites for the current group), but it was of no use because the entire step is bypassed. Invite Anyone's settings does have the option to remove their step from Group Creation workflow, but that disables both BB and IA invite steps.


PS: I managed to fix the "Create and sync a LearnDash group" using CSS, so that part of the issue may have been my fault.

**Comment by eisenwasser** [comment]
@JPvanRooyen Thanks for the feedback

**Comment by JPvanRooyen** [comment]
Hi guys, quick question: I would like to contribute by submitting new bugs as I find them, following your contributing guidelines. However, the righthand column is not available to assign the project label or any other label (see screenshot attached).

I would want to keep posting bugs on unrelated threads.
Feel free to let me know how you'd like me to go about.
<img width="1713" alt="Screen Shot 2020-07-14 at 11 35 44" src="https://user-images.githubusercontent.com/6604224/87410282-63fddf00-c5c6-11ea-8942-e98a3cf6a309.png">

**Comment by kent-carlo** [comment]
**Create and sync a LearnDash group** option is already showing in latest buddyboss platform plugin.
https://www.loom.com/share/604f289f8e49465ebe5f73348e5add7e
