### ISSUE TITLE
Tool tip option for displaying field Instructions

### ISSUE THREAD

**Issue by tonymeltone** [buddyboss/buddyboss-platform#1184]
Profile fields have "Instructions" which I use to tell the user how the data should be entered or the standard for the data.  
These instructions appear on the profile during editing.  See below.

![CurrentInstructions](https://user-images.githubusercontent.com/61334272/87161764-fa629580-c292-11ea-982d-7022316743d8.JPG)

To make a cleaner UI and to economize on profile editing real estate I would like field instructions to be displayable as a tool tip.
An option on the field below the instructions value would allow the back-end user to define if those instructions should be displayed as a tool tip.

![ProfileSetup](https://user-images.githubusercontent.com/61334272/87161972-48779900-c293-11ea-8cc9-bbc848a79358.JPG)

If selected, when a user is editing their profile they will see this tool tip to the right of the field name rather than the printed instructions.  When the user hovers over the tool tip icon the instructions would be displayed.  This would have to be a different operation on a mobile device (tap?)

![ToolTipInstructions](https://user-images.githubusercontent.com/61334272/87162140-85dc2680-c293-11ea-8156-31f388949061.JPG)

**Comment by marienel21** [comment]
Hi @tonymeltone,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
