### ISSUE TITLE
Ability to Clean Media and Media Offloading

### ISSUE THREAD

**Issue by welshlamb10** [buddyboss/buddyboss-platform#1189]
**Is your feature request related to a problem? Please describe.**
I have a large community. Our server storage is running up near quota fast. Over 200gb already and it's difficult to maintain backups and will only worsen moving forwards.

I have seen this fantastic plugin that will delete content/posts from a group based on a date. Although this does not remove the media that was attached (which is whats using up space). Here it is: https://wordpress.org/plugins/bp-bulk-delete/

**Describe the solution you'd like**
It would be great that you can select a date to delete content from in a group that will remove the posts and the media. This would free up valuable space of the server. If all post content was offloaded this would also help.

**Describe alternatives you've considered**
Integration of  BP- Bulk Delete plugin https://wordpress.org/plugins/bp-bulk-delete/
Although a modification that will also delete the post media from the media library.

It would also be great if there was an option on BuddyBoss to attach cloud storage for offloading media, saving space on servers.

**Comment by marienel21** [comment]
Hi @welshlamb10 ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
