### ISSUE TITLE
Group Privacy Options defaults

### ISSUE THREAD

**Issue by ld-rlph** [buddyboss/buddyboss-platform#1190]
**Is your feature request related to a problem? Please describe.**
Some members create a group without even finishing the settings and leave that just as is and it shows first on the list.

**Describe the solution you'd like**
I just want to add an option in the admin panel a default privacy option for creating a group (Public, Private, Hidden).

**Describe alternatives you've considered**

**Support ticket links**
https://secure.helpscout.net/conversation/1223367095/83003

**Comment by ExoGeek** [comment]
This is a good suggestion !

In the meanwhile this suggestion is implemented in buddyboss core, you can use a filter : 

```
function pf_groups_group_status_before_save( $status ){
	if ( bp_current_user_can( 'bp_moderate' ) ) {
		return $status;
	} else {
		if ( $status == 'public' ){
			return 'hidden';
		} else {
			return $status;
		}
	}
}
add_filter( 'groups_group_status_before_save', 'pf_groups_group_status_before_save')
```

**Comment by marienel21** [comment]
Hi @ld-rlph ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
