### ISSUE TITLE
Hidden and private group forum's replies visible to non member. 

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#1204]
**Describe the bug**
Hidden and private group forum's replies visible to non member. 
Also visible in BB widgets 'Forum discussion Views list' and 'Forum recent replies'. 
https://prnt.sc/ti6wjs

**To Reproduce**
1. Create a hidden and private group with forums. 
2. Post replies as a member
3. View as a non member on Activity feed. 

**Expected behavior**
Hidden and private forum replies should not be visible to non member on Activity feed. 

**Screenshots**
https://www.loom.com/share/1255cf12d85c45dea5769f0c05a55960

**Support ticket links**
https://secure.helpscout.net/conversation/1195266278/77950?folderId=3701249

**Comment by buddyedilene** [comment]
A client also experienced the same issue. Please see the screenshots. https://prnt.sc/tha579, https://prnt.sc/ticky9

**Comment by KartikSuthar** [comment]
@Anve-sri @buddyedilene @ankitguptaindia @mohit-buddyboss 

I have tried to reproduce this issue, I have checked the client sites and it's happing due to the different privacy of the group and forum. I have tried to regenerate this scenarios into local but I can not produce it.
http://somup.com/cYi3hX6hmQ

Can you please provide me steps/video on how the different privacy setup into the system for the groups and associated forums?

**Comment by Anve-sri** [comment]
@KartikSuthar The issue is only happening because of the different privacy. I have asked the customer to check if the difference in privacy causes this issue. But i am not sure about @buddyedilene issue.

**Comment by buddyedilene** [comment]
@KartikSuthar I checked on the client's site, both have the same privacy setting which is Hidden. Non-members can see the updates in the Activity feeds which should not be the case. Please check this video. https://www.loom.com/share/eb51bb2716b54e8593a5469f28b0e1b7
