### ISSUE TITLE
'Custom' date type not working in Profile fields. 

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#1230]
**Describe the bug**
I am trying to add just the year to the profile field and I have selected the custom field type and entered "Y" for the year but it still shows the full Day, Month.

**To Reproduce**
1. Go to 'BuddyBoss > profile fields'
2. Add new field
3. Select type 'Date' , Date format ' Custom' . 
4. Put 'Y' in the input field. 
5. In frontend , you will see date and Month also. But i just placed 'Y'. 

**Expected behavior**
Only year option should be in frontend.

**Screenshots**
https://prnt.sc/tk5e7h
https://prnt.sc/tk5eid

**Support ticket links**
https://secure.helpscout.net/conversation/1227757514/83679?folderId=3701249

**Comment by buddy4kp** [comment]
Hello @Anve-sri 
Yes, you are right, Even you put 'Y' only in the input field at Select type 'Date', Date format ' Custom' It will show full date at frontend side at signup. Because We have selected date type. 
But When we are showing it at profile page after signup, it will show only "Y"(2020) year as we have selected date format to "Y".
Please see attach the screenshot.
![image](https://user-images.githubusercontent.com/65785731/87933163-5d7dd480-caaa-11ea-89ea-1dcbf8b1165f.png)
@eisenwasser  Please let us know your suggestion also.
Thanks.

**Comment by buddy4kp** [comment]
Hello @Anve-sri 
As discussed with @eisenwasser , We do not need to apply any changes in it.
As the date format is only using to show the date in this format at Frontend side, We should always ask full date at profile fields if the user selected type as Date. Let's take one example.
At the initial stage, if the user select date type and set date format to "Y".  After that, he enters the values at this field as the only year and now he changes the date format to "d-m-Y" that time we should have the full date then only we can show in this format.
Thanks.
