### ISSUE TITLE
Add option "Last Name & First Name" Display Name Format

### ISSUE THREAD

**Issue by mailalaki** [buddyboss/buddyboss-platform#1240]
hi, please add new option in Display Name Format as "Last Name & First Name". its very useful in school platforms. thanks

**Comment by janakkaneriya007** [comment]
Hi @mailalaki 

The option you are talking is already in place. You can find it here:  BuddyBoss > Settings > Profiles
https://prnt.sc/uvi2cp

**Comment by marienel21** [comment]
Hi @mailalaki,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
