### ISSUE TITLE
PDF Documents Preview not working when website is hosted in Flywheel Cloud Platform

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1259]
**Describe the bug**
When a website is hosted with Flywheel Cloud Platform, this renders the document preview blank as Flywheel Cloud Platform has separated the WordPress core files away from the root directory. The WordPress core files are actually symlinked from the /.wordpress directory now. The updater might be looking where the WordPress core files are, but your files are in the www directory.

**To Reproduce**
1. Host website in Flywheel Cloud Platform
2. Enable Document in BuddyBoss > Settings
3. Upload a PDF document
4. See error on frontend, document preview not working

**Notes**
Reference ticket: https://secure.helpscout.net/conversation/1204905782/79738/

**Expected behavior**
The document preview must still work and not render blank

**Screenshots**
<img width="878" alt="Screen-Shot-2020-06-25-at-12 45 17-AM" src="https://user-images.githubusercontent.com/58522224/88461605-94535080-ced7-11ea-8841-dd3379f5e304.png">

**Support ticket links**
https://secure.helpscout.net/conversation/1215499495/81761

**Comment by chetansatasiya** [comment]
https://secure.helpscout.net/conversation/1229984811/84058/

**Comment by chetansatasiya** [comment]
@emmanoctaviano I am closing this issue because this issue is related to his server and even if yoi disable the platform and theme his server can't creating the PDF preview image so I replied him and I give some suggestions and helpful link to properly install those addon for the preivew.

Some Helpful links:

https://deliciousbrains.com/pdf-preview-images-wordpress-real-world
https://wordpress.org/support/topic/bropken-pdf-thumbnail-generation/#post-11461858
https://wordpress.org/support/topic/pdf-thumbnails-no-longer-being-generated/
