### ISSUE TITLE
Subscriber user role wp-admin URL restriction

### ISSUE THREAD

**Issue by ld-rlph** [buddyboss/buddyboss-platform#1260]
**Is your feature request related to a problem? Please describe.**
Users with Subscriber user role are able to access /wp-admin URL

**Describe the solution you'd like**
Users with Subscriber user role should not be able to access /wp-admin URL, if ever they go to this URL they will just be redirected to home page or wherever page that it should be.

**Support ticket links**
https://secure.helpscout.net/conversation/1219114231/82368

**Comment by marienel21** [comment]
Hi @ld-rlph,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
