### ISSUE TITLE
Add Likes to Forums

### ISSUE THREAD

**Issue by sanjayxe** [buddyboss/buddyboss-platform#1281]
**Is your feature request related to a problem? Please describe.**
As an admin, I want more ways to understand the engagement of my forums, so I can better understand the ROI of BuddyBoss.

As a poster on the forums, I'd like to see reactions to my posts, as this will motivate me to post more.

As a user of the forums, I want to contribute but replies aren't always appropriate. By liking posts, I can share my feedback in a quick way.

**Describe the solution you'd like**
I'd like to see BuddyBoss implement likes in forums, similar to how they are implemented in activity, groups, and more. Because the existing infrastructure is already built, this should be a high payoff, low effort feature enhancement. 

**Describe alternatives you've considered**
The alternative would be using another plugin and trying to hack together a reaction system outside of BuddyBoss.

**Support ticket links**
N/A

**Comment by TokumeiJG** [comment]
Totally agree.
So many times I want to "like" a post but replying with "thanks" or "yes" just annoys everyone involved.

**Comment by marienel21** [comment]
Hi @sanjayxe,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team

**Comment by GaryJones** [comment]
https://roadmap.buddyboss.com/p/enhancements-to-reactions-hB5Teb is the specific item for adding Reactions to forums.
