### ISSUE TITLE
Make the "<number> Comments" text link on activity updates expand/show the comments on the activity update

### ISSUE THREAD

**Issue by scarabcoder** [buddyboss/buddyboss-platform#1286]
**Is your feature request related to a problem? Please describe.**
As a member in a BuddyBoss community viewing an activity update, clicking the "5 Comments" (example) text link doesn't expand the comments for that activity update, which is unexpected behavior. Currently it opens the comment form.

**Describe the solution you'd like**
It should expand the comment section for the activity update instead of opening the comment form. 

**Describe alternatives you've considered**
n/a

**Support ticket links**
n/a

![bb activity update](https://user-images.githubusercontent.com/4871271/88942040-94887e80-d23e-11ea-964a-674ea9aed925.png)

**Comment by marienel21** [comment]
Hi @scarabcoder,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
