### ISSUE TITLE
Add target="_blank" option for external links in messages

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#1287]
Could you add `target="_blank"` option for external links in messages?
![image](https://user-images.githubusercontent.com/4050715/88846961-cd553300-d1ff-11ea-90e9-c9fc25220d46.png)

**Describe alternatives you've considered**
How it is working in activity feed:

![image](https://user-images.githubusercontent.com/4050715/88846855-a5fe6600-d1ff-11ea-8e9a-c7261831ac9d.png)

Related comment: https://github.com/buddyboss/buddyboss-platform/issues/1004#issuecomment-665880643

- buddyboss-platform 1.4.7

**Comment by marienel21** [comment]
Hi @AiratHalitov ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
