### ISSUE TITLE
BB REST API : Activity Endpoint - Add "before" filter to get activites before a date

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1310]
Hi,

In the activity endpoint "wp-json/buddyboss/v1/activity/", we do have a filter parameter "after" but we don't have the filter parameter "before".

Could you add it ?

It's very usefull on mobile device when you have to implement "Load More items" when reaching the bottom of the already loaded activities. Using "page" parameter is not suitable because new items can be added on top in the meantime.

Regards,
ExoGeek

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
