### ISSUE TITLE
playing video or music with Copied download link

### ISSUE THREAD

**Issue by mailalaki** [buddyboss/buddyboss-platform#1312]
hi,
how to use "Link of MP4 Uploaded Document" to playing instead of direct download file?
Is it possible to do this personalization for video playback by writing an action/filter?

**Comment by marienel21** [comment]
Hi @mailalaki 

Thank you for adding this issue, however as per the [notes](https://github.com/buddyboss/buddyboss-platform#support), this repository is not suitable for support issues. I’m going to close this ticket but if the problem is still outstanding please submit a support request at your [BuddyBoss.com](https://www.buddyboss.com/) account.

Thanks,
Marienel - BuddyBoss Product Team
