### ISSUE TITLE
Disallow/Warning for duplicated email invites

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1323]
**Is your feature request related to a problem? Please describe.**
Avoid duplication of email invites

**Describe the solution you'd like**
A warning message or totally disallow duplication of email invites. also a warning if the user is already registered.

**Support ticket links**
https://secure.helpscout.net/conversation/1238945486/85553

![duplicate-invite](https://user-images.githubusercontent.com/58522224/89715586-1e6fde80-d9d9-11ea-9a2c-4c103a2a91fa.JPG)

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel - BuddyBoss Product Team
