### ISSUE TITLE
BB REST API - Activity Endpoint - Add missing filter parameters

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1354]
Hello,

There're some missing parameters to the endpoint Activity (to have an exhaustive list of parameters, you can see all parameters available in the method BP_Activity_Activity::get() in file class-bp-activity-activity.php).

- **order_by**  : enum = 'id', 'user_id', 'component', 'type', 'action', 'content', 'primary_link', 'item_id', 'secondary_item_id', 'date_recorded', 'hide_sitewide', 'mptt_left', 'mptt_right', 'is_spam'
- **show_hidden** : boolean
- **meta_query**
- **fields** : string

Enhancement :
- **privacy** : should be an array and not a single enumeration
- **scope** : Missing "public" value (to be able to retrieve the same activities displayed on the web page https://demos.buddyboss.com/online-communities/) (**)

(**) For the moment, when you try to list all activities (when user is logged in - GET {{host}}/wp-json/buddyboss/v1/activity), REST API do not returns activities with bp_activity.privacy = "friends". It only returns activities with privacy = ["public", "all members", "only-me"]

Regards

**Comment by g000m** [comment]
It appears that you also cannot simply filter 'type'. BP_Activity_Activity lacks a filter for $excluded_types before it starts being formatted into SQL. In my case, I want to exclude 'joined_group'.

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
