### ISSUE TITLE
Monetization Feature: BuddyBoss Social Group enrollment / access can be also purchased as a product

### ISSUE THREAD

**Issue by 007ke** [buddyboss/buddyboss-platform#1359]
**Is your feature request related to a problem? Please describe.**
Monetization Feature: BuddyBoss Social Group enrollment / access can be also purchased as a product 

**Describe the solution you'd like**
Currently, the BuddyBoss Social Group can ONLY be accessed upon invitation to join and once it's approved by the group manager / moderator.  We can add a Monetization feature to this by making it (as an option) a woocommerce product. 
 
**Describe alternatives you've considered**
(1) When creating a new social group, we can additionally add a woocommerce product mapping or product ID section somewhere in the admin side bar panel. This is an optional field if an admin wishes to monetise the social group access / enrolment. 
(2) When in the WooCommerce product creation, we can add a BuddyBoss Group section immediately under the LearnDash Course and LearnDash Group sections. 

This way, we can monetise not only purchasing a social group but it can work as a product bundle of learndash course(s) + learndash group(s) + buddyboss social group(s).

Use case can be ..... either buy a learndash course(s) for on-demand self learning while a buddyboss social group can be more premium if the learner needs coaching ( can be via zoom) and dedicated support (groups forums), etc ....

**Comment by marienel21** [comment]
Hi @007ke ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
