### ISSUE TITLE
JetPack Widget visibility is not working with buddyboss-platform

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#1365]
**Describe the bug**
When buddyboss-platform plugins is active JetPack widget visibility module's button doesn't showing in widgets.

**To Reproduce**
1. Install [JetPack plugin](https://wordpress.org/plugins/jetpack/) and enable Widget Visibility module (`/wp-admin/admin.php?page=jetpack_modules`)
2. Go to widgets page (`/wp-admin/widgets.php`) and try to change widget visibility
3. Activate buddyboss-platform and try to change widget visibility again
4. The visibility button will disappear (`style="display: none;"` will be added)

**Expected behavior**
`style="display: none;"` shouldn't be added to elements

**Screenshots**

JetPack Widget Visibility:

![widgets](https://user-images.githubusercontent.com/4050715/90403927-155acd80-e0bb-11ea-95a6-f00a72c9e943.gif)
---

Could you fix it ASAP, because this bug interferes with other plugins settings.

**Configuration:**

- buddyboss-platform v1.4.9
- JetPack v8.8.2
- WordPress v5.5

**Jira issue** : [PROD-920]

[PROD-920]: https://buddyboss.atlassian.net/browse/PROD-920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by AiratHalitov** [comment]
The bug is still actual:

- buddyboss-platform v1.5.3
- JetPack v9.0.2
- WordPress v5.5.1

Related: https://github.com/Automattic/jetpack/issues/17555

**Comment by jeherve** [comment]
This seems to happen here:
https://github.com/buddyboss/buddyboss-platform/blob/cfc0def7d95ad8a65455f67032dcf9d379824663/src/bp-core/admin/js/settings-page.js#L494-L505

I believe you may be able to fix this by being more specific when targetting buttons; instead of targetting all containers using the `display-options` class, you may be able to be a bit more specific to only target the buttons you want to hide?
