### ISSUE TITLE
New Concept: Crowdfunding for BuddyBoss joint custom feature development

### ISSUE THREAD

**Issue by 007ke** [buddyboss/buddyboss-platform#1375]
**Is your feature request related to a problem? Please describe.**
Many BuddyBoss customers would like to have their custom features implemented in the theme/platform. BuddyBoss has a customisation service as a revenue model so a conflict of interest. BuddyBoss customers then end up getting the same done remotely at a cost and usually such developments are ad-hoc and no clear documentation to further enhance and usually leads to duplication and waste.

**Describe the solution you'd like**
The ideal solution would be to have an in-between (joint customer and BuddyBoss) business model whereby such custom developments are crowdfunded whereby making it more affordable and yet maintaining such developments within the BuddyBoss team with little to zero revenue sacrifice.

**Describe alternatives you've considered**
Create a new "Custom Features" section listing all the requested features as a separate project with a crowdfunding element like the total project cost estimated, minimum funding needed to start the project, etc... This way it will provide the transparency to the customers, connect likewise customers together for that project funding AND the decision to roll-out such new features and functionalities are transparent and fact based rather than judgmental on one or few members.

This will open up new business and revenue model for BuddyBoss as well as happy and satisfied clients. 

@eisenwasser , if you like this concept then i have a few more.

**Comment by 007ke** [comment]
i was reading this https://github.com/buddyboss/buddyboss-platform/issues/849 and all the threaded comments and saw the clear missed opportunity, duplication and loss of potential revenue....  where Tony could not wait and ready to hire an outside developer while Michael and BuddyBoss were liking this and placing it in the roadmap for sometime in near or distant future.

**Comment by eisenwasser** [comment]
@007ke 

`Many BuddyBoss customers would like to have their custom features implemented in the theme/platform. BuddyBoss has a customisation service as a revenue model so a conflict of interest.`

That is not our philosophy at all. Our goal is for the core product to have all of the features out of the box that users need for a social network. We offer custom work for those who ask, but the product is the driving engine of this company and of our future services. The product needs to be the best it can be, this is what both our customers and our paying clients want.

I would love to see the day when clients are only requesting custom features that are really unique to their product because all of the mainstream things are in the core product already. This was our main motivation for creating BuddyBoss Platform to begin with; BuddyPress development was not adding the things all our clients kept asking for over and over, and we kept building ad-hoc solutions. We wanted to improve the core product to have everything in it out of the box. This has made it easier for our current clients too; now when they request a feature, if possible, we can incorporate it into the core product and then we take over maintaining it in core. In the BuddyPress days that was not possible.

As for the feature requests, we currently receive an incredible amount of requests, many hundreds per week. It is not possible to build all of this in any reasonable amount of time. So we take the most common requests and build them and/or schedule them in the roadmap, and for the others we tell the customer they would have to build it on their own, or they can ask us to build it custom if they need it done "now". Building it in the core product is substantially more time consuming than building it custom for a client, so we have to pick and choose what we work on at any given time for the core product, and that list is going to be only a handful of major items at a time. If you look at our roadmap, and see how much we have released in the past 12 months... we are moving very aggressively here, and actively hiring/growing the team so we can accelerate. I promise you we are going as fast as we can!

`I think there should be a Buddyboss user community.`
Yes!! We do plan to introduce an official community. It would be a huge benefit to everyone. I appreciate all of your feedback.

**Comment by 007ke** [comment]
Hi Michael, we understand that you and BuddyBoss team is doing the max and continuously rolling out new features more in alignment to the BuddyPress community. This is great. Also if Crowdfunding is not the company policy, it's understandable. I agree with you totally on this.

My suggestion was more from the online learning community (and not social network community alone) and more specific to the BuddyBoss Theme and related plugins (be it LearnDash, Lifter or other LMS). This community has been built over a period of time starting from Social Learner and now grown size-able to include other WP related LMS.  These 2 features have been requested by many users in the past https://github.com/buddyboss/buddyboss-platform/issues/1359 and https://github.com/buddyboss/buddyboss-platform/issues/1358 which is apt for both.. theme and platform.

As there is no transparency or a dedicated place where we can request and check the response for the new feature; while raising it here on github as an issue is not an ideal solution & quickly gets buried down, my request if you can create something on the main website with transparency. Most clients would find it logical to raise it on the BuddyBoss website than github.

Thanks for always hearing and supporting us mate.

Cheers

**Comment by marienel21** [comment]
Hi @007ke,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
