### ISSUE TITLE
More profile field information on member listing / directory, please

### ISSUE THREAD

**Issue by tonymeltone** [buddyboss/buddyboss-platform#1377]
Hello -

I would like to see the member listing be more capable of providing quick information to the user.  We run a system for connecting athletes with coaches and athletic programs.  When a coach looks at a list of athletes they want to get a quick thumbnail sketch of who that athlete is.  For example, see screen shot (with some information scratched out):

![image](https://user-images.githubusercontent.com/61334272/90580406-c5e9cf80-e196-11ea-9550-e2d520f28430.png)

I would like to see options on a profile field to specify that it shall be be displayed on the member listing summary.  If it is "checked" that it should be displayed on the listing view, it would be good if there were a few other parameters like placement order and field title (instead of High School it might be HS on the profile listing),  In our case, we organize the fields in two columns.

There are some other bits of data you see on this profile listing, too:
You see the Gamipress achievement icons and you see and icon that specifies is a specific field has a value in it (video URL field).  Would be great to have the ability to place short code content in the member listings too.

**Comment by marienel21** [comment]
Hi @tonymeltone,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
