### ISSUE TITLE
BB REST API - Messages Endpoint - Add content_stripped field to the response for easily display emoji

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1379]
**Is your feature request related to a problem? Please describe.**
It could be great to add field "content_stripped" to the response of messages endpoint. For the moment we "only" have "content.raw" and "content.rendered" but these fields contains the html representation of an emoji. 

**Describe the solution you'd like**
I think the code to add to the function "prepare_message_for_response" in file class-bp-rest-messages-endpoint.php is :

`'content_stripped'  => html_entity_decode( wp_strip_all_tags( $message->message ) ),`

**Describe alternatives you've considered**
none

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
