### ISSUE TITLE
Irony - There's No Buddyboss User "Community"

### ISSUE THREAD

**Issue by tonymeltone** [buddyboss/buddyboss-platform#1388]
It would be really nice if there was a Buddyboss sanctioned user community where Buddyboss users could exchange ideas and information and help each other.  It's odd there isn't one already given that Buddyboss itself is a community builder.....

**Comment by TokumeiJG** [comment]
10000000% agree.  We can learn so much from each other.
Also, maybe with a coder marketplace to hire developers who know BuddyBoss

**Comment by tonymeltone** [comment]
007ke   It doesn't need to be closed with outcomes...We need to be able to collaborate with each other.

**Comment by marienel21** [comment]
Hi @tonymeltone,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
