### ISSUE TITLE
BuddyBoss as Dropbox lite: Add the Option to Share Document Folders with Specific Members

### ISSUE THREAD

**Issue by mr-motus** [buddyboss/buddyboss-platform#1390]
The current privacy options when posting/sharing documents are nice, but adding an option to share with specific members only (e.g. like Facebook does it) would be a great addition in my opinion. I think this would be especially powerful when sharing document folders: Dropbox lite anyone?

P.S. Perhaps this option should only be available for certain user roles to prevent abuse of storage, etc. If so, the admin should be able to select these roles.

**Comment by marienel21** [comment]
Hi @mr-motus,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
