### ISSUE TITLE
Display Post Type Comments Within Groups Instead Of Main Activity Feed

### ISSUE THREAD

**Issue by King-Ding** [buddyboss/buddyboss-platform#1423]
**Is your feature request related to a problem? Please describe.**
Currently comments that are posted in LearnDash lessons (post type) can be displayed on the main activity feed. This can be done by going to '_BuddyBoss > Settings > Activity > Posts in Activity Feeds_' in the wordpress admin area. The problem is the lack of options to otherwise display these comments in other areas of buddyboss, such as within groups.

**Describe the solution you'd like**
When a course is tied to a group, course actions are optionally added to the group’s activity stream. Group admins can determine which actions to allow in their group.

**Describe alternatives you've considered**
This plugin created by buddyboss does the trick (*almost): https://wordpress.org/plugins/buddypress-learndash/. It would be great if this was integrated into the buddyboss platform. The plugin generally works, with the exception of a few bugs.

Another important side note that is lacking in the current and proposed functionality is the ability to nest comment responses under the relevant parent comment - that would be revolutionary!

**Comment by 007ke** [comment]
I agree 100%

**Comment by marienel21** [comment]
Hi @King-Ding ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team

**Comment by contemplate** [comment]
Where exactly is this request on the roadmap?  I have numerous clients waiting for this feature.
