### ISSUE TITLE
Add Activity Shortcode to show in different pages

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1430]
**Is your feature request related to a problem? Please describe.**
Customers wants to insert activity feed to certain parts of the page they designed

**Describe the solution you'd like**
a functionality similar to https://wordpress.org/plugins/bp-activity-shortcode/

**Support ticket links**
https://secure.helpscout.net/conversation/1254119106/88238?folderId=3701258

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel - BuddyBoss Product Team
