### ISSUE TITLE
Improve display of "Group Types" filter on profile page

### ISSUE THREAD

**Issue by mailalaki** [buddyboss/buddyboss-platform#1435]
Hi, The "Group Types" option in the "My Groups" section of the user's personal profile page needs to show only the "Group Types" that the person is a member of in one of the subgroups.

![Untitledsd](https://user-images.githubusercontent.com/13551603/91869760-7f629d80-ec8b-11ea-97c4-4e21316c1193.png)

**Comment by marienel21** [comment]
Hi @mailalaki ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team

**Comment by afrocult** [comment]
Hi @mailalaki , I wonder how in the meantime you solved the issue given that I am facing the exact problem.
@marienel21, could you please point me to the feature on the public roadmap so I can +1 it. I could not find it.
