### ISSUE TITLE
Media Component : Add scope "message" to get medias sent and/or received in messaging

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1445]
**Is your feature request related to a problem? Please describe.**
I would like to have a page where a user can view all of his photos received/sent by message. But because this scope is not yet implemented, I can't create it easily. 

1) Could you add a new scope to bp_media_default_scope to be able to get photos received/sent in the message component ?
2) Could you also add that scope to the media endpoint (BB REST API).
3) Could you add a new tab in "photos" to show photos received/sent by message ?

![image](https://user-images.githubusercontent.com/46819762/92138479-b1503d00-ee0e-11ea-9313-09cebafc7f57.png)

**Describe the solution you'd like**
none

**Describe alternatives you've considered**
none

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
