### ISSUE TITLE
BB REST API - Media Endpoint : Add scope "all"

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1446]
**Is your feature request related to a problem? Please describe.**
Could you add the scope "all" as a valid parameter ?

```
$params['scope'] = array(
	'description'       => __( 'Scope of the media.', 'buddyboss' ),
	'type'              => 'array',
	'items'             => array(
		'enum' => array( 'friends', 'groups', 'personal' ),
		'type' => 'string',
	),
	'sanitize_callback' => 'bp_rest_sanitize_string_list',
	'validate_callback' => 'rest_validate_request_arg',
);
```

Become

```
$params['scope'] = array(
	'description'       => __( 'Scope of the media.', 'buddyboss' ),
	'type'              => 'array',
	'items'             => array(
		'enum' => array( 'all', 'friends', 'groups', 'personal' ),
		'type' => 'string',
	),
	'sanitize_callback' => 'bp_rest_sanitize_string_list',
	'validate_callback' => 'rest_validate_request_arg',
);
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
