### ISSUE TITLE
Move closed issues and PRs to Released in GitHub Project

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#1449]
There is too many closed issues and PRs in project columns which are not moved to Released
Filter: https://github.com/buddyboss/buddyboss-platform/projects/1?card_filter_query=is%3Aclosed
Screenshot:
![image](https://user-images.githubusercontent.com/4050715/92253563-1710f780-eee9-11ea-8bbc-152f4ecf6ca2.png)

@eisenwasser 
Could you move them to [Released](https://github.com/buddyboss/buddyboss-platform/projects/1#column-7178318)?

It would be more convenient to navigate through the project.

Or should it be done automatically?

**Comment by marienel21** [comment]
Hi @AiratHalitov,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
