### ISSUE TITLE
Posting multiple hyperlink in a activity breaks the ability to post.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1474]
**Describe the bug**
If you paste into a group feed or activity text that contains more than one hyperlink its seems to break giving error "There was a problem posting your update try again" It does not allow posting.
This appears to be a problem with the link preview function
Note: It seems working fine for Admin user roles.
Please refer to the screencast:
http://somup.com/cYQ6fnXuDa

**To Reproduce**
1. Login as subscriber user role.
2. Goto activity feeds page and try to paste a paragraph that contains multiple hyperlinks.
3. Click on the post-update button.

**Support ticket links**
https://secure.helpscout.net/conversation/1240667936/85858?folderId=3701248

**Comment by mehulkaklotar** [comment]
@furqanbb @sourabhmatolia  this is because of comment moderation settings in WP backend. Subscribers are checked for moderation if they post more than 2 links bydefault. There is a setting WP Dashboard -> Settings -> Discussion -> Comment Moderation -> Hold a comment in the queue if it contains 2 or more links. https://prnt.sc/uer2oy
