### ISSUE TITLE
BB REST API - Notifications Endpoint (new_message) : Store thread id in the response

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1493]
**Is your feature request related to a problem? Please describe.**
This enhancement has the same explanation that the issue #1490.

If I want to open the full thread based on the notification, I need to extract the thread id (30) from the string link_url.

```
    "id": 1131,
    "user_id": 1,
    "item_id": 379,
    "secondary_item_id": 12,
    "component": "messages",
    "action": "new_message",
    "date": "2020-09-15T09:10:13",
    "is_new": 1,
    "description": {
      "rendered": "<a href=\"http:\/\/buddyboss.localhost\/members\/exogeek\/messages\/view\/30\/\">Neville sent you a new private message<\/a>"
    },
    "link_url": "http:\/\/buddyboss.localhost\/members\/exogeek\/messages\/view\/30\/",
    "rest_actions": "",
    "object": "user",
    "object_id": 12,
```

**Describe the solution you'd like**
Could you use fields "object" and "object_id" to store the ID of the thread ?

```
    "object": "thread",
    "object_id": 30,
```

**Describe alternatives you've considered**
Another solution could be to use the field "secondary_item_id"

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
