### ISSUE TITLE
BB REST API - Create the Lost Password Endpoint

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1502]
**Is your feature request related to a problem? Please describe.**
Could you please add a route in the REST API which helps a user to reset his password when he lose it.

If that can help you, here is the code I used to use with BuddyPress : 

[class-pf-lost-password-endpoints.php](https://github.com/buddyboss/buddyboss-platform/files/5231323/class-pf-lost-password-endpoints.txt)

**Describe the solution you'd like**
Create an endpoint to reset lost password

**Describe alternatives you've considered**
none

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
