### ISSUE TITLE
Add button to learndash sidebar that takes students back to the tethered group

### ISSUE THREAD

**Issue by King-Ding** [buddyboss/buddyboss-platform#1511]
**Is your feature request related to a problem? Please describe.**
When students are in a course but they want to go to the tethered group, it can take a few unnecessary clicks to get there.

**Describe the solution you'd like**
There's already a button that allows users to exit the lesson/topic and review the course information and syllabi, but it would be great if there was a button besides this that also allowed students to go to the tethered classroom.

**Describe alternatives you've considered**
Adding the following line to 'learndash/ld30/learndash-sidebar.php' (after line 75) allows students to visit the parent groups archive, but I'm not sure how to adapt that so that students are sent to the tethered group:

`<a href="<?php bp_group_permalink(); ?>" class="course-entry-link back-to-tethered-group"><span><i class="bb-icons bb-icon-chevron-left"></i><?php echo sprintf( esc_html_x('Group List', 'link: Back to groups', 'buddyboss-theme'), LearnDash_Custom_Label::get_label( 'course' ) );?></span></a>`

I trust that this would be a simple inclusion, should you consider implementing it into the theme.

**Comment by marienel21** [comment]
Hi @King-Ding ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
