### ISSUE TITLE
Create a new email instance for [{{{site.name}}}] {{poster.name}} mentioned you in a forum discussion/update

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1512]
**Is your feature request related to a problem? Please describe.**
Customer doesn't get an email when s/he got mentioned on a forum discussion, reply or update. I think it will be if you can add this feature.

[Note: Right now, they get a notification]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Support ticket links**
https://secure.helpscout.net/conversation/1260825393/89406

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel - BuddyBoss Product Team
