### ISSUE TITLE
Profile > Courses returns 404 when Learndash Courses URL is nested

### ISSUE THREAD

**Issue by marilyn9425** [buddyboss/buddyboss-platform#1518]
**Describe the bug**
Member Profile > Courses tab return 404 error when Learndash URL is nested

**To Reproduce**
1. Go to Settings > Permalinks
2. On LearnDash Permalinks section, change courses slug to a nested one (nested/courses)
3. Course archive displays correctly
4. Members Profile Courses 

**Expected behavior**
Display courses instead of 404 page

**Screenshots**
https://www.loom.com/share/b837c0270e9e40a6bfd1fe592111669b

**Support ticket links**
https://secure.helpscout.net/conversation/1270601038/91134

**Comment by HQRaja** [comment]
It's been six months since it was first reported here, and four months since I reported it in a support ticket, with no resolution in sight. Please fix this ASAP - my client has been asking about this on an almost daily basis now. I know you guys are busy with the app but please don't neglect known issues because of it, as they're affecting existing websites of paying customers.

**Comment by sourabhmatolia** [comment]
@HQRaja Added this for the next milestone. Thanks.

**Comment by sourabhmatolia** [comment]
@HQRaja 

Issue mentioned above is released in BuddyBoss Platform v1.5.9

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-9/

Please update the plugin to see the latest changes.

Thank you.

**Comment by HQRaja** [comment]
@sourabhmatolia Thank you - much appreciated.
