### ISSUE TITLE
Country Codes in Profiles type field : "Phone"

### ISSUE THREAD

**Issue by AmineBAIK1** [buddyboss/buddyboss-platform#1551]
Hi, 
There is some enhancement here to do. 
The phone format International and ## are no longer userfriendly and intuitif 
We should have a country code format ! With select or automatically detect 
When we use scripts from international tel input they works but they are not synchronized and integrated with buddy boss x-profile fields. 
We hope to see a multi country code select phone in the future. 
It can looks like this with buddyboss touch
![screenshot-2](https://user-images.githubusercontent.com/46829598/94277232-907c9280-ff49-11ea-81a8-18962769e497.png)

**Comment by marienel21** [comment]
Hi @AmineBAIK1 ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
