### ISSUE TITLE
Registration pages are self assigning when Activity settings is changed

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1553]
**Describe the bug**
When setting BuddyBoss as Registration Form in BuddyBoss > Settings > Registration, this opens up pages in Registration Pages in BuddyBoss > Pages > Registration Pages. The initial selection would be "select a page", but when you change something in BuddyBoss > Settings > Activity, the Registration pages are self assigning

**To Reproduce**
1. Go to BuddyBoss > Settings > Registration. Enable BuddyBoss Registration in Registration Form
2. Go to BuddyBoss > Pages > Registration Pages, see these are all in "Select a page" choices (don't select anything, keep as is)
3. Go to BuddyBoss > Settings > Activity. Change something, like  enable/disable: Automatically check for new activity posts
4. Go back to BuddyBoss > Pages > Registration Pages, see error. The pages are already assigned

**Expected behavior**
The Registration Pages must not be changed

**Screenshots**
https://drive.google.com/file/d/1mk8gvKnvOJEWFSw_dZxCGqd6QEdtLtCu/view?usp=sharing
original issue by customer: https://vimeo.com/461016238/0a652425e8

**Support ticket links**
https://secure.helpscout.net/conversation/1228780073/83847

**Jira issue** : [PROD-909]

[PROD-909]: https://buddyboss.atlassian.net/browse/PROD-909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by surajkrsingh** [comment]
@emmanoctaviano @dipskakadiya 
I am not sure, It is a bug or expected behaviour because the register page is self assign in the dropdown when BuddyBoss > Settings > Registration is enabled

In other cases, it is not assigning the page to the register field.
1. If you disabled the BuddyBoss > Settings > Registration and try to update any settings then it remains as it is.
2.  If you enabled the Registration settings and assigned a different page than register and after that, you try to update any settings then it remains the same.

The conclusion, if you enabled the Registration settings then the register form page field should be selected. 
It can't be empty.

Please consider the above points and let me if still need a fix for this.

**Comment by dipskakadiya** [comment]
@surajkrsingh As per my opinion, I think, if Registration settings enabled and registration page not selected then, it's okay if it automatically selected because if page not selected then registration link will be broken.

**Comment by surajkrsingh** [comment]
@emmanoctaviano 
Please check the above comment and let me know if you have any thoughts.

I am going to close this issue.

**Comment by emmanoctaviano** [comment]
@dipskakadiya @surajkrsingh the behavior actually inconsistent. if we leave blank pages for registration, this is okay. But this changes when an Activity option is enabled/disabled in BuddyBoss > Settings > Activity. This is auto assigning. If this is the default behavior, then should it be auto assigning the registration pages after it is reloaded? Need your insights as well

**Comment by surajkrsingh** [comment]
@chetansatasiya 
The customer has reported the issue for pages auto assigning when we save the activity settings.

I found the code line which is intensely mapping the admin pages when saving the activity settings. 
Maybe has some purpose.
Code line - https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-core/admin/settings/bp-admin-setting-activity.php#L71

On commit - https://github.com/buddyboss/buddyboss-platform/commit/3e75fccbf5471ee3995d01eae9e0d668df645945 

We need your help to validate the issue.
I think this is expected behaviour but as the customer complains.

Please let us know your suggestion on this.
