### ISSUE TITLE
I want to rename the components of the Buddyboss. For example I want to call Groups as Communities. Forums as Discussions. Activity as Feed or something like that.

### ISSUE THREAD

**Issue by vinaysagar4u** [buddyboss/buddyboss-platform#1585]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by marienel21** [comment]
Hi @vinaysagar4u ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team

**Comment by segunolamidegitup** [comment]
Any update on this request. Do we have it done?
