### ISSUE TITLE
BB REST API - Messages Endpoint : Add filter to not display [messages] field in response

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1605]
**Is your feature request related to a problem? Please describe.**
When you use the REST API to list all threads of a user, the response contains all threads + all messages (inside each thread). This can be usefull in some cases but it also make the query very heavy (regarding data transfered or execution time).

For example, in my case (Buddyboss is hosted on a private server) :

```
### GET Messages
GET {{host}}/wp-json/buddyboss/v1/messages
Authorization: Bearer {{auth_token}}
```
_Response code: 200 (OK); Time: 5767ms; Content length: 230758 bytes_

=> 230 Kb and 5,7 sec to list all threads !

**Describe the solution you'd like**
Add a filter "display_messages" (boolean) to include or not all messages in the response.

**Describe alternatives you've considered**
none

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
