### ISSUE TITLE
dequeue CSS & JS when unused

### ISSUE THREAD

**Issue by g000m** [buddyboss/buddyboss-platform#1617]
**Is your feature request related to a problem? Please describe.**
Non-buddyboss pageloads are bloated with unused BB JS & CSS assets. I want to remove bloat and increase performance
issue #34 mentions similar intentions.

**Describe the solution you'd like**
When buddyboss-platform detects that it's not being used, stop & unload assets, or at least give me a way to. 

**Describe alternatives you've considered**
Simplest might be to put in something like a `do_action( 'bp_not_a_page' )` at [bp-core-catchuri.php#L274](https://github.com/buddyboss/buddyboss-platform/blob/dev/src/bp-core/bp-core-catchuri.php#L274) so that I can 

```
add_action( 'bp_not_a_page', function () {
	remove_action( 'wp_enqueue_scripts', 'bp_enqueue_scripts', 10 );
	remove_action( 'wp_enqueue_scripts', 'buddyboss_theme_scripts' );
	remove_action( 'wp_enqueue_scripts', 'bbp_enqueue_scripts', 10 );
} );
```

**Comment by marienel21** [comment]
Hi @g000m ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
