### ISSUE TITLE
Single Sign On with password sync for keycloak 

### ISSUE THREAD

**Issue by prasadajith** [buddyboss/buddyboss-platform#1631]
**Is your feature request related to a problem? Please describe.**
enabling single sign on for community

**Describe the solution you'd like**
login interface should be a login that authenticates through SSO, password reset should reset the password in keycloak, not in wordpress database

**Describe alternatives you've considered**
have considered Single sign on plugins of wordpress... The Ux is very messy, or adons are irrationally expensive

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @prasadajith ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
