### ISSUE TITLE
Private Messaging Restriction/Control (Stop Spam)

### ISSUE THREAD

**Issue by King-Ding** [buddyboss/buddyboss-platform#1635]
**Is your feature request related to a problem? Please describe.**
Spam is the problem. With the Messaging component activated, anyone can sign up to a buddypress/buddyboss website and send spam messages to all members.

**Describe the solution you'd like**
A simple toggle or dropdown in the backend that allows admins to restrict private messaging between certain wordpress user roles. For example, all members can only message admins (i.e: user role 'customer' can message site admin only).

**Describe alternatives you've considered**
This plugin does the trick, but it's outdated and provides minor errors in conjunction with buddyboss platform plugin.
https://wordpress.org/plugins/bp-messaging-control/

**Comment by marienel21** [comment]
Hi @King-Ding ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
