### ISSUE TITLE
Multisite - Cover image upload size limit error

### ISSUE THREAD

**Issue by mehulkaklotar** [buddyboss/buddyboss-platform#1638]
**Describe the bug**
When uploading cover image, error for max file size is shown, but in php.ini both `upload_max_filesize` and `post_max_size` is set to 32MB but error says my file is more than 2 mb so can't upload.

There is a site meta stored for each site or root site, called `fileupload_maxk` which is 1500 bydefault when site activated, this meta is affecting the whole scenario.

**To Reproduce**
1. Go to Profile  > Edit cover image
2. Upload cover image more than 10 mb

**Expected behavior**
It should allow files upload according to my server php settings.

**Screenshots**
https://prnt.sc/v0hd4r

**Jira issue** : [PROD-903]

[PROD-903]: https://buddyboss.atlassian.net/browse/PROD-903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ExoGeek** [comment]
On my website, without any default modifications, it is limited to 5Mo

![image](https://user-images.githubusercontent.com/46819762/99535686-8c00b300-29a9-11eb-861f-035ed1084b16.png)

**Comment by sadrul** [comment]
For wp single site, the issue occurs for members & groups avatar, photo and cover photo. The maximum upload size is taking from function "bp_attachments_get_max_upload_file_size()" in "buddyboss-platform/src/bp-core/bp-core-attachments.php" This function is not used anywhere else.

Proposed solution:
if we use the function wp_max_upload_size (provided by wp, checks ini settings and is used by wp default media) instead of a hardcoded number, it would solve the issue - https://prnt.sc/wfxcri 


Note For wpmu site:
- In wpmu network settings, default value 1500KB https://prnt.sc/wfw3vu it can be changed and the value is used as maximum upload size for members & groups avatar, photo and cover photo
- It has been set during network setup by this code (coming from wp default) https://prnt.sc/wfvy8f and all subsites use this network settings
- In platform, "bp_core_get_root_options()" function also uses 1500 as default value in network options https://prnt.sc/wfwaoj
