### ISSUE TITLE
Quoted Replies are Missing

### ISSUE THREAD

**Issue by mikeemesser** [buddyboss/buddyboss-platform#1648]
**Is your feature request related to a problem? Please describe.**
It is custom to almost every forum software since the 1990s to have the possibility to quote the posting or comment one replies to - either completely or only the specific piece of text. The latter is often done by selecting the text one wants to quote.

**Describe the solution you'd like**
In addition to an "Answer" button there should also be a "Quote" button. If no text is selected, the quote button would quote the complete posting the user is referring to. If text is selected, only the selected text becomes the quote. The user would then write the comment below the quoted text. In addition, the quotes text should be editable before the comment is sent. If the user quotes a quote, the previous quote should also be displayed. Every quote should contain at least the name of the author, possibly also the date and time, like "John Doe wrote on October 3, 2020 at 12.30 p.m.:"

This would be handy both for forum comments as well as for comments to status updates or any other piece of content which can be commented.

**Comment by marienel21** [comment]
Hi @mikeemesser ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
