### ISSUE TITLE
Filters for Status Updates in Activity Stream (only connections and/or people I follow)

### ISSUE THREAD

**Issue by mikeemesser** [buddyboss/buddyboss-platform#1649]
**Is your feature request related to a problem? Please describe.**
For a community of more than a few dozen users it is totally unfeasible that _every_ user sees _every_ status update from _every_ other user. This overloads the activity stream and renders it next to useless.

**Describe the solution you'd like**
Admins as well as users should have the possibility to limit status updates in the activity stream to those from connections and from people I follow (separate settings). Admins can set the default behavior, users cann override it if they like in their preferences.

**Comment by TokumeiJG** [comment]
I would love this as well.

**Comment by TokumeiJG** [comment]
To add to this, it might be good to have "suggestions" in the activity feed like in Facebook/Twitter.

If filtering (like @mikeemesser suggests) is on, new users wouldn't see anything (unless they turned on all activity), so maybe have "You may know..." or "You may want to join..." suggestions.

It feels a bit like BuddyBoss is mostly focused on learning stuff like Lifter, but there are some great opportunities for niche social networks as well if some of the features were improved.

**Comment by marienel21** [comment]
Hi @mikeemesser ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
