### ISSUE TITLE
Non-logged in users can use Search even when Private Network enabled

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1650]
**Is your feature request related to a problem? Please describe.**
When setting Private Network enabled and enabling the Homepage for public view, this still gives non-logged in users the ability to use the search function, thus showing search results

**Describe the solution you'd like**
Add restriction for Search Results when Private Network is enabled

**Support ticket links**
https://secure.helpscout.net/conversation/1290449854/100227

**Comment by ExoGeek** [comment]
This is also a concern for me ! Private network should remain private...

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel - BuddyBoss Product Team
