### ISSUE TITLE
Add functionality to edit comments same as Edit Activity

### ISSUE THREAD

**Issue by shohel** [buddyboss/buddyboss-platform#1653]
**Is your feature request related to a problem? Please describe.**
Would be great if we provide option to edit comments as well same as Edit Activty.

**Describe the solution you'd like**

- Go to the activity page
- check comment posted on activity

**Describe alternatives you've considered**
User should be able to edit his/her comments same as Facebook, Slack

**Support ticket links**
N/A

**Comment by marienel21** [comment]
Hi @shohel ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
