### ISSUE TITLE
"My Forums" Widget

### ISSUE THREAD

**Issue by TokumeiJG** [buddyboss/buddyboss-platform#1672]
**Describe the solution you'd like**

I would like a new widget option that displays a list (with links) of the forums the current user is subscribed to.

This will help user experience on community sites with many forums and sub-forums so the user can directly jump to their subscribed forums. (In the case they are subscribed to many forums, have pagination at the bottom of the widget.)

**Describe alternatives you've considered**
Scoured bbPress forums and plugins, but cannot find anything...

**Comment by marienel21** [comment]
Hi @TokumeiJG ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
