### ISSUE TITLE
Could not post pasted image on Activity feed

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1690]
**Describe the bug**
When copying image from web and pasting this on Activity feed, this cannot be posted. but when you add some text, this works fine.

**To Reproduce**
1. Direct copy any image from web (right click - copy)
2. Paste on Activity Feed and post
3. See error

**Expected behavior**
Pasted images should be posted with or without other characters included.

**Screenshots**
https://drive.google.com/file/d/1lCZWL_N-jYf2cRPqZcMHsOK4O4Aj1lX2/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1305315468/102665
https://secure.helpscout.net/conversation/1364953063/114407
https://secure.helpscout.net/conversation/1547915561/148438/

**Note**
Maybe related with this issue as HTML is being stripped down when posting in Activity feed
https://github.com/buddyboss/buddyboss-platform/issues/1688

**Comment by ngolwalkar** [comment]
In the mentioned file below, there is already a check to see if the content is empty and before that, they are already striping the Html, Also they are checking if the media component is active and if the media get posted, so it seems intentional because we already have the Media component to post the image/s. So that it is not accepting the image by just copy and pasting the image.
File : buddyboss-platform\bp-templates\bp-nouveau\includes\activity\ajax.php
Line number: From 536 to 557.

**Comment by kishanjasani** [comment]
@emmanoctaviano This feature is intentionally removed from the platform. Users can use media upload functionality to upload the media.

**Comment by CentralCrypto** [comment]
Someone tryed to do that to enable paste images into activity feed?
