### ISSUE TITLE
Let people automatically connect each other after a email invite request has been accepted

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1695]
**Is your feature request related to a problem? Please describe.**
When a user invites another person using the component Email Invite, we know that there's a connection between them.

For the moment, the invited person receives an email to join the community. After he created his account, either the inviter or the invited person needs to make a friend request **manually** (they have to find each other using the search component).

It could be a great idea to let the choice to the inviter to automatically creates a friend request as soon as the invited has created his account.

**Describe the solution you'd like**
1. In the page `https://localhost/members/neville/invites/sent-invites/`, add a checkbox for "Create a connection request as soon as the invitation has been accepted".
2. In the registration process, hook the system to check if the user has been invited by someone in the community (there may be multiple users) + checkbox in the form (point 1.) is checked => If this is the case, automatically create friends requests for all users.

**Describe alternatives you've considered**
At least create a notification to inform the inviter that one of his invitation has been accepted.

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
