### ISSUE TITLE
Lower resolution of images in post gallery (activity feed)

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1699]
**Is your feature request related to a problem? Please describe.**
When you post image gallery inside the activity feed, used thumbnails are a lot more larger than the zone. 

This is bad for performance and for bandwidth expense.

![BuddyBoss_Image_Size](https://user-images.githubusercontent.com/46819762/97279501-5ef23200-183b-11eb-8d87-165e6adf9d9d.png)
As you can see, Image zone is 268x221 but the image is 1600x1067.

Related issue #1696 

**Describe the solution you'd like**
Search in the available image size (already created), the one that fit best (depending on device).

**Describe alternatives you've considered**
Creates specific size thumbnails for feed.

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by philraymond** [comment]
It's not only in the activity feed - it's in the forum, too. Come on BuddyBoss!

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
