### ISSUE TITLE
Voice Recording

### ISSUE THREAD

**Issue by ragnabnet** [buddyboss/buddyboss-platform#1701]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when our user has a problem to upload their voice. Right now the document upload feature in buddyboss can't accomodate them well for uploading their voice. We need this feature to function well because we're working on a language course site.

**Describe the solution you'd like**
A dedicated button and system that can make user record and (or) upload their voice note on every buddyboss comment system. And the files that you need to accomodate is: .mp3 and .m4a (these 2 files extension are the files that produced by all of the phone recorder system). I already added this .m4a extension in your document system but nothing works.

**Describe alternatives you've considered**
No alternative, this is just to enchance your document feature

**Support ticket links**
Doesn't has

**Comment by marienel21** [comment]
Hi @ragnabnet,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team

**Comment by weismannweb** [comment]
im willing to support this development if anyone else wants it built, i would do it for cost

**Comment by lwildes65** [comment]
Hello,

We would like to add this feature as well.  Were you able to find a solution?

Best,

Loren
