### ISSUE TITLE
Google Meet

### ISSUE THREAD

**Issue by ragnabnet** [buddyboss/buddyboss-platform#1702]
**Is your feature request related to a problem? Please describe.**
Hello, i'm a full time teacher for 5 years now. In this pandemic, a lot of teachers teaching using either zoom or google meet for teaching. But actually in the education field, most of the teacher use are the google meet because it can connected to google classroom and the other google products. But why buddyboss only accomodate zoom? Since the biggest education platform for video meeting is google meet not zoom.

**Describe the solution you'd like**
Please make an buddyboss platform pro to be synced with the google meet too.

**Describe alternatives you've considered**
None

**Support ticket links**
None

**Comment by davidmabelle** [comment]
+1

**Comment by salemwarrad** [comment]
+2

**Comment by Felipemauah** [comment]
> **Is your feature request related to a problem? Please describe.**
> Hello, i'm a full time teacher for 5 years now. In this pandemic, a lot of teachers teaching using either zoom or google meet for teaching. But actually in the education field, most of the teacher use are the google meet because it can connected to google classroom and the other google products. But why buddyboss only accomodate zoom? Since the biggest education platform for video meeting is google meet not zoom.
> 
> **Describe the solution you'd like**
> Please make an buddyboss platform pro to be synced with the google meet too.
> 
> **Describe alternatives you've considered**
> None
> 
> **Support ticket links**
> None

+4

**Comment by Felipemauah** [comment]
+4

**Comment by marienel21** [comment]
Hi @ragnabnet ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team

**Comment by GabrielVDN** [comment]
+5

**Comment by Jabe64** [comment]
+6 Please reopen
