### ISSUE TITLE
Default content &#8203; when adding gif and refactor gif module correctly

### ISSUE THREAD

**Issue by mehulkaklotar** [buddyboss/buddyboss-platform#1713]
**Describe the bug**
When adding gif into activity, message or any other place where gif is supported, we add `&#8203;` into the content by default. Actually it is not needed because we already check for any validation when post is being added in ajax.

**To Reproduce**
1. Go to activity post form
2. Click on add gif and any add gif and update the post without any content.
3. Check the activity content in db.

**Expected behavior**
It should not automatically add `&#8203;` in content.

**Comment by ExoGeek** [comment]
I suggest to not insert "&#8203;". 

- It increases storage of the DB for nothing
- When you use BB REST API, it's "more difficult" to verify if the content is empty or not.

**Comment by sourabhmatolia** [comment]
@dkvasani 

Please take over this task.
Talk to Mehul if you have question.

**Comment by dkvasani** [comment]
Hello @sourabhmatolia 

I have removed &#8203; this from gif module.
During the testing when we do any comment on activity and if we upload document or photos at that time also  &#8203; this content is stored.
Can you please confirm do i need to remove from that document and photos modules ?

**Comment by jitendrabanjara1991** [comment]
@mehulkaklotar @chetansatasiya @sourabhmatolia 
This issue has been fixed in this PR - [https://github.com/buddyboss/buddyboss-platform/pull/1832](https://github.com/buddyboss/buddyboss-platform/pull/1832)
I checked with the fix/1713 branch and it seems working fine.  [https://screencast-o-matic.com/watch/crV1DPPqyt](https://screencast-o-matic.com/watch/crV1DPPqyt)
