### ISSUE TITLE
Actively commented postings should stay on top (or go back up to the top) of the Activity Feed

### ISSUE THREAD

**Issue by mikeemesser** [buddyboss/buddyboss-platform#1729]
**Is your feature request related to a problem? Please describe.**
Whenever someone comments on a posting in the activity feed (or a group feed) that posting stays on it's original chronological place in the list. This is rather confusing because it prevents active postings from becoming more prominent in the activity feed.

**Describe the solution you'd like**
Intended behavior would be *at the very least* that a posting, which is recently commented on, goes on top of the users acitivity feed.

In a more complicated scenario the activity feed would also keep other factors in mind, for example, if the posting received x likes in it's first y minutes after being posted - then it would go back to the top again.

But for the time being I'd be happy if the former solution would work out.

**Describe alternatives you've considered**
There is one really bad alternative: The plugin "BuddyPress Activity Bump" achieves this effect by changing the time stamp of the original posting every time it is liked or commented on. This is a *very* bad idea, because it creates a wrong impression on *when* something has been posted - which is important for context but could also have legal implications. So, please don't go this route!

**Comment by marienel21** [comment]
Hi @mikeemesser ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
