### ISSUE TITLE
BB REST API - Notifications Endpoint (group_invite) : Store invite_id in a field

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1752]
**Is your feature request related to a problem? Please describe.**
This enhancement has the same explanation that the issue #1490.

If I want to accept and reject a group invitation, I need "invite_id" which is only stored in rest_actions->accept>endpoint and rest_actions->reject->endpoint.

```
  "id": 363,
  "user_id": 12,
  "item_id": 1,
  "secondary_item_id": 0,
  "component": "groups",
  "action": "group_invite",
  "date": "2020-07-12T20:40:38",
  "is_new": 0,
  "description": {
    "rendered": "<a href=\"http:\/\/buddyboss.localhost\/members\/bb-neville\/groups\/invites\/?n=1\">You have an invitation to the group: Foodie’s Group<\/a>"
  },
  "link_url": "http:\/\/buddyboss.localhost\/members\/bb-neville\/groups\/invites\/?n=1",
  "rest_actions": {
    "status": "Pending",
    "accept": {
      "endpoint": "http:\/\/buddyboss.localhost\/wp-json\/buddyboss\/v1\/groups\/invites\/3",
      "method": "PATCH",
      "link_url": "http:\/\/buddyboss.localhost\/groups\/foodies-group\/"
    },
    "reject": {
      "endpoint": "http:\/\/buddyboss.localhost\/wp-json\/buddyboss\/v1\/groups\/invites\/3",
      "method": "DELETE",
      "link_url": "http:\/\/buddyboss.localhost\/groups\/foodies-group\/"
    }
  },
```

**Describe the solution you'd like**
Could you please store that id in secondary_item_id field.

**Describe alternatives you've considered**
none

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
