### ISSUE TITLE
Change Group Message "Send Message" button state when clicked

### ISSUE THREAD

**Issue by marilyn9425** [buddyboss/buddyboss-platform#1758]
**Is your feature request related to a problem? Please describe.**
When a group have many members, sending group message to all members will take time but there is no indication that the message is "sending" or in the process of sending. The button is still clickable.

Client will think that it's not working (or sending) that will lead them to click the button again which will send the message as much as how many times the button is clicked.

**Describe the solution you'd like**
Change the label and/or make the button not clickable. Maybe add a spinning icon as an indication that its loading (sending)

**Describe alternatives you've considered**
Advised to add a snippet of JS and CSS to make the button not clickable and change the button label.
_Note: initially tried to add a **disabled** attribute but the sending function did not work afterwards._

**Support ticket links**
https://secure.helpscout.net/conversation/1332507681/107836/

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel - BuddyBoss Product Team
