### ISSUE TITLE
Group Information / Description Sidebar Widget

### ISSUE THREAD

**Issue by TokumeiJG** [buddyboss/buddyboss-platform#1786]
Right now, even with group header settings set to small, the top area of a group (header image, group image, group description, organizers etc) takes up a lot of vertical space and posts are hard to see immediately. 

ie like this https://prnt.sc/vl5yi9

It would be great if there was a widget for "Group Description" that could be put in the sidebar.  Something like the sidebar on a subreddit where groups could describe themselves, have posting rules etc.

Being able to remove the description from the top will allow more posts to be shown immediately and improve UX as well as (possibly) increase user activity.

**Comment by marienel21** [comment]
Hi @TokumeiJG ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
