### ISSUE TITLE
Allow notifications for enrolled users in a Course when commenting is enabled

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1793]
**Is your feature request related to a problem? Please describe.**
When Comments is enabled on a Course, add the ability to notify to other users who are enrolled in the course that someone commented on the course

**Support ticket links**
https://secure.helpscout.net/conversation/1330747544/107453/

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel - BuddyBoss Product Team
