### ISSUE TITLE
Shortcode

### ISSUE THREAD

**Issue by nosfatsug** [buddyboss/buddyboss-platform#1813]
I would like the ability to add shortcode to the groups and forums pages to show stock data.  

For example - group "A" is a specific company stock - and I'd like to add shortcode to show that stock's performance data (current price, % increase/decrease) which I can using other themes.

**Comment by marienel21** [comment]
Hi @nosfatsug ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
