### ISSUE TITLE
Discourse Integration

### ISSUE THREAD

**Issue by davidmabelle** [buddyboss/buddyboss-platform#1824]
Please integrate Discourse  https://www.discourse.org/

**Comment by marienel21** [comment]
Hi @davidmabelle ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
