### ISSUE TITLE
Select and move multiple files at a time

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1828]
**Is your feature request related to a problem? Please describe.**
Moving files is done one by one, which will require more time if you need to move multiple files.

**Describe the solution you'd like**
To be able to multi-select the files and move them together.

**Screenshot**
![one](https://user-images.githubusercontent.com/58522498/100126520-01dcb100-2eb9-11eb-9ec7-d88b562323c2.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1347581398/110751/

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel - BuddyBoss Product Team
