### ISSUE TITLE
Create Smart Thumbnails with face detection

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1830]
**Is your feature request related to a problem? Please describe.**
Wordpress crop images per fixed position. This often generates thumbnails with faces being cut out (especially when you upload vertical photos of people in which their faces is on the top of the photo).

![image](https://user-images.githubusercontent.com/46819762/100205467-74737e00-2f05-11eb-8447-0c79d3dae22a.png)

You can find on github some PHP code to create smart thumbnails automatically (face detection).

**Describe the solution you'd like**
1. Add an option to create smart thumbnails (centered on the face or the object)
2. Because face detection algo returns a square around the face or the gravity center of photo, store that information in the database (using custom field)
3. Return that custom field in the BB REST API (/buddyboss/v1/medias). In that way, any app using REST API can center the image on the gravity point/square.

**Describe alternatives you've considered**
none

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
