### ISSUE TITLE
Support for GraphQL or WPGraphQL for optimizing BB REST API requests

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1837]
**Is your feature request related to a problem? Please describe.**
As you should have already experienced, WP REST API is great BUT it is very slow and returns a lot of data not always needed (a lot of KB is transferred). When you use WP REST API on a mobile App or desktop application, you can't really optimize your app except by implementing an internal cache system.

After making some research on how to improve my app, I've came to the technology of **GraphQL** used by all major websites in the world (facebook, twitter, pinterest, shopify, ...) and developped by Facebook.

With GraphQL you can implement single query to fetch a lot of data, you can specify what field you need in the response, ... This seems to be awesome !

I've seen that an implentation of **GraphQL** has been made for Wordpress. **WPGraphQL** is an **open source project**. 

It could be very great to implement WPGraphQL support in BuddyBoss Platform.

**Describe the solution you'd like**
Implement WPGraphQL (or GraphQL) support in BuddyBoss Platform.

**Describe alternatives you've considered**
none

**Support ticket links**
none

**Comment by blackge** [comment]
This would be really helpful.

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
