### ISSUE TITLE
Improve loading time of like button in activity feed posts

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#1848]
**Is your feature request related to a problem? Please describe.**
When clicking like button in activity feed posts it take some time to load.

**Describe the solution you'd like**
Customer suggest: change the icon on the end user's browser instead of waiting for the server respond.

**Describe alternatives you've considered**
​Demo site:​
​https://www.loom.com/share/bb04646b9de04bfcaad302e6cef7dffd
​
​Customer site: 
​https://www.loom.com/share/1e222bdcc390418a8d26cebacc40612c

**Support ticket links**
https://secure.helpscout.net/conversation/1349350764/111225

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel - BuddyBoss Product Team
