### ISSUE TITLE
User can post an activity even when photos are still uploading

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1850]
**Is your feature request related to a problem? Please describe.**
When a user creates an activity with some photos, the button "Post Update" is enabled even if some photos are still loading (uploading).  

If user click (too fast) on the button "Post Update" before photos are uploaded, there's no warning and the activity is created with already uploaded photos.

**Describe the solution you'd like**
- Disable the button "Post update" until all photos are uploaded.
- Show a loading icon on the button (so the user now that photos are still uploading)

**Describe alternatives you've considered**
- When user click on the button, show a warning

**Support ticket links**
none

**Comment by lumpysimon** [comment]
We've run into this and it is causing us problems, especially for users with slower upload speeds.

Users have no idea that they must not click the 'Post update' button while images are still uploading, and there is no indication that images have not uploaded until they view their post/reply and see they are not there.

The solution proposed by @ExoGeek sounds like it should be pretty straightforward to implement and would solve the problem.

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
