### ISSUE TITLE
Add Documents count Groups page

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1856]
**Is your feature request related to a problem? Please describe.**
Users would like to know the number of documents uploaded in Group

**Describe the solution you'd like**
Add Documents count like Members and Photos

**Support ticket links**
https://secure.helpscout.net/conversation/1349629609/111311
![documents-count](https://user-images.githubusercontent.com/58522224/100854185-9fd90880-34c3-11eb-8b71-e4c2bceec691.JPG)

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel - BuddyBoss Product Team
