### ISSUE TITLE
Setting to limit the number of levels of subgroup

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1876]
**Is your feature request related to a problem? Please describe.**
The hierarchy of the group can go deep without any limits.

**Support ticket links**
https://secure.helpscout.net/conversation/1357026619/112972/

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel - BuddyBoss Product Team
