### ISSUE TITLE
Add a language profile field compatible with WPML

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1905]
**Is your feature request related to a problem? Please describe.**
When you create a multilingual social network, it would be useful to attach the preferred language in the user profile.

For the moment, you can install and translate buddyboss. But you don't have an easy way to let people choose/save their language. With WPML, the language is stored in a cookie. If user uses another browser, his previous choice is not applied.

**Describe the solution you'd like**
Create a new profile field "Language".
Detect if WPML is used => display languages configured in WPML.
When user is logged in, use that field to set the website language.

Ps : You also have to use that field when emails are sent (to sent emails in the user language)

**Describe alternatives you've considered**
none

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
