### ISSUE TITLE
BB REST API - WPML compatibility - Localize the response using wpml_language argument value

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1912]
**Is your feature request related to a problem? Please describe.**
WPML adds by default a new argument "wpml_language" to each GET route. This argument is used to localize the respone of the REST API request.

This should work out of the box if : 

1) REST API uses __() functions (_OK for buddyboss_)
2) Wordpress language context is modified based on this argument (_KO for buddyboss_)

Localized rest respoine can be useful for example in the routes : 
- Description of the notifications
- Title of the activity
- Display_date of a message
- ...

`GET {{host}}/wp-json/buddyboss/v1/notifications?is_new=1&per_page=10&wpml_language=fr`

**Describe the solution you'd like**
When the argument wpml_language is set in the REST API request, return the translated text.

**Describe alternatives you've considered**
none

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
