### ISSUE TITLE
Add LinkedIn and Windows Live to Social Login component

### ISSUE THREAD

**Issue by Spectrabytes** [buddyboss/buddyboss-platform#1929]
**Is your feature request related to a problem? Please describe.**
Helps driving professional audiences to the site as LinkedIn and Microsoft has the largest professional base in the world.

**Describe the solution you'd like**
Add LinkedIn and Windows Live to Social Login component

**Describe alternatives you've considered**
Tried miniOrange. But, it is blocking some images. Hence would be nice if LinkedIn and Windows were added so that I can use native Buddyboss App instead of a 3rd party plug-in.

**Support ticket links**
Frontend/Styling issues : Profile photo not visible   #112526

**Comment by wbeem** [comment]
Upvote!

**Comment by marienel21** [comment]
Hi @Spectrabytes ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
