### ISSUE TITLE
Message Improvement

### ISSUE THREAD

**Issue by dipskakadiya** [buddyboss/buddyboss-platform#1962]
Some code refactoring required to fix some performance-related core logic 

- With the Message thread ajax, We sending all recipients lists for every thread. it'll be a little heavy with a large network 
We should send recipients with some limit like 10 and we also need to send total recipients with thread objects.  

- We need to provide separate ajax to get message thread recipients so we can support pagination.

- One major refactoring we can do is, we can move our message logic based on Rest endpoint instead of ajax, by this change we no need to maintain two chunks of code.  

-----

Customer Query for the Reference

Slow SQL queries from group message causing the private messages and message notification to load so slow and sometimes causing 500 internal error, it happens when there are thousands of group members in a group message thread.
This is the slow SQL query reported by client: https://prnt.sc/wiqzai

--------
https://secure.helpscout.net/conversation/1470954591/134010
Test Group and with only one member the Group message had no delay and acted as one would expect.
some other Group - with over 49 members it has this massive delay.

Related HS Tickets:
https://secure.helpscout.net/conversation/1371027857/115494/
https://secure.helpscout.net/conversation/1388206152/118467/
https://secure.helpscout.net/conversation/1470954591/134010/
https://secure.helpscout.net/conversation/1567963949/152658/

**Comment by furqanbb** [comment]
https://secure.helpscout.net/conversation/1388206152/118467/

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1381207954/117117

**Comment by jrbuddyboss** [comment]
https://secure.helpscout.net/conversation/1339384046/109091
https://secure.helpscout.net/conversation/1345163480/110088

**Comment by carmeltajanlangit** [comment]
https://secure.helpscout.net/conversation/1465700691/132961/

**Comment by angelic-joyce** [comment]
https://secure.helpscout.net/conversation/1541739892/147484?folderId=4465050

**Comment by justinpatrickkeller** [comment]
We have 120+ Groups activity using Group Messages 20-30 of them are over 100+ people and 100+ are more than 50 people. I'm realizing that anytime someone sends a group message my site becomes momentarily unresponsive and current users get 500 errors for a few minutes while the server struggles to catch up... What's weird is the CPU Logs and RAM Logs look okay. (the server is an 8CPU 32 GB RAM VultrHF on Cloudways)... Hopefully this issue when resolved will help?

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1511400505/141891/

**Comment by jitendrabanjara1991** [comment]
This issue has two PRs.
-  https://github.com/buddyboss/buddyboss-platform/pull/2125 , I have fixed below changes.
Issue - If 1,000 members available in the message thread, then all the members were loading at the same time.
Solution - I have added logic, When open message thread at that time display only 20 members and after that add pagination for next member list. Same thing done in API side.

- https://github.com/buddyboss/buddyboss-platform/pull/2827
Issue - Slow SQL queries from group message causing the private messages and message notification to load so slow and sometimes causing 500 internal error, it happens when there are thousands of group members in a group message thread.
This is the slow SQL query reported by client: https://prnt.sc/wiqzai
 -  Above issue will cover in this PR - https://github.com/buddyboss/buddyboss-platform/pull/2827.

cc - @sourabhmatolia @firozwp

Thanks.

**Comment by sourabhmatolia** [comment]
Associated PR merged for release.

Re-opened issue based on comment here:
https://github.com/buddyboss/buddyboss-platform/issues/1962#issuecomment-909317993

Thanks.

**Comment by furqanbb** [comment]
https://secure.helpscout.net/conversation/1624763639/162935/

**Comment by abbymontano** [comment]
https://secure.helpscout.net/conversation/1633289518/164416/

**Comment by aclaoallen24** [comment]
https://secure.helpscout.net/conversation/1690900585/172973/
