### ISSUE TITLE
The activity featured image of the Blog posts and Custom Post types should also be centered or fitted.

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1965]
**Is your feature request related to a problem? Please describe.**
Featured images are not centered or fitted in the container on the activity feed.

**Describe the solution you'd like**
The featured image must be shown just like when posting an image using the media uploader.

**Screenshot**
![feat](https://user-images.githubusercontent.com/58522498/103141130-c0932780-472a-11eb-9761-b5a507d119d0.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1370164691/115338/

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel - BuddyBoss Product Team
