### ISSUE TITLE
Copy paste images to text editor

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1966]
**Is your feature request related to a problem? Please describe.**
Some users assume that copy-pasting works on the text editor, but after sending the message or posting it, the image is gone.

**Describe the solution you'd like**
Should be able to copy-paste images without using the media uploader.

**Support ticket links**
https://secure.helpscout.net/conversation/1373801519/115950/

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel - BuddyBoss Product Team
