### ISSUE TITLE
To have a list of the members in the profile page to whom you sent a connection request

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1987]
**Is your feature request related to a problem? Please describe.**
Currently, when you go to the profile page > connections, only the My Connections tab, and Request tab are only available, but no option to see the list of members to whom you sent a connection request

**Describe the solution you'd like**
To have another tab for the list of members to whom you sent a connection request
![feature](https://user-images.githubusercontent.com/58522498/103444946-188cd980-4ca9-11eb-8f5f-ea2129278d4e.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1382235745/117324/

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel - BuddyBoss Product Team
