### ISSUE TITLE
Allow Members to create Sub-Groups based on available Parent groups only

### ISSUE THREAD

**Issue by zachkinsey** [buddyboss/buddyboss-platform#2003]
**Is your feature request related to a problem? Please describe.**
At the moment members are able to create Parent groups while sub-group functionality is enabled. This allows members to create unnecessary Parent groups and destroys any attempt any organization of Groups.

**Describe the solution you'd like**
To have an option where Members are only allowed to create sub-groups based on currently available Parent groups.

**Comment by marienel21** [comment]
Hi @zachkinsey ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team

**Comment by NyekoObote** [comment]
Any update?
