### ISSUE TITLE
Activation page should be excluded in the private network

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2013]
**Is your feature request related to a problem? Please describe.**
When using the Private Network, the admin needs to manually add the activation page in the public content for their users to be able to activate their account. Otherwise, they will not be able to access the activation page when clicking the link on the activation email.

**Describe the solution you'd like**
Activation page should be excluded in the private network

**Support ticket links**
https://secure.helpscout.net/conversation/1387324093/118332/

**Comment by marilyn9425** [comment]
https://secure.helpscout.net/conversation/1461745080/132254/

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
