### ISSUE TITLE
Unhide messages

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2025]
**Is your feature request related to a problem? Please describe.**
There is no easy way to unhide messages.

**Describe the solution you'd like**
A separate folder or page for hidden messages

**Support ticket links**
https://secure.helpscout.net/conversation/1388200697/118466/

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
