### ISSUE TITLE
To have a page where your followers are listed

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2040]
**Is your feature request related to a problem? Please describe.**
The **[(BB) Members I'm Following](https://i.ibb.co/25hysqk/follow.jpg)** widget is redirecting to the main members directory 

**Describe the solution you'd like**
To have a page that lists your followers

**Support ticket links**
https://secure.helpscout.net/conversation/1395132468/119635

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
