### ISSUE TITLE
Registration widget

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2048]
**Is your feature request related to a problem? Please describe.**
There is a Login widget but no registration widget.

**Support ticket links**
https://secure.helpscout.net/conversation/1391897626/119075/

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
