### ISSUE TITLE
Block Feature : Add the ability to block group invitation to avoid spam

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#2054]
**Is your feature request related to a problem? Please describe.**
On my social buddyboss network, members are allowed to create groups and I've got a problem of spam : some users continually invite other members to join their groups. For the moment, there's no way to avoid such spam. Each time, a member reject the invitation, a new invitation can be sent...

Even when the invitee blocks the inviter, the inviter is still able to invite the member to join his group.

Ps : I know that there's the option "Restrict Group invites to members who are connected." but in some cases, this is too restrictive because I want to let people invite others without having to be connected.

**Describe the solution you'd like**
I would like to find a solution to avoid such spam. The invitee should be able to "block" an invitation (no more invitation for that group). 

On the page "Group Invites", add a button to "Reject and Block" the group invitation. The inviter won't be able to invite that member anymore. 

**Describe alternatives you've considered**
Add a button to open a menu where the invitee can : 

1) Block the inviter : the same functionnality as blocking a user
2) Block group invitation : inviter won't be able to invite the member anymore

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
