### ISSUE TITLE
The filtered search results (by post type etc) are great, but the initial result, which lists the first three per category, do not appear to be the three most relevant

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2059]
The filtered search results (by post type etc) are great, but the initial result, which lists the first three per category, do not appeat to be the three most relevant (most useful). 
Please refer to the screenshot: [https://prnt.sc/x81s1e](https://prnt.sc/x81s1e).
Here search results are showing for "membership" keyword but if you take a closer look at the pages section you will see the most relevant results are not showing in All Results page. 
Now please refer to my second screenshot: [https://prnt.sc/x8216g](https://prnt.sc/x8216g). 
Here you can see the most relevant results are showing at top when I click on the Pages section.

**Describe the solution you'd like**
Possible solution could be adding "ORDER BY relevance DESC" at buddyboss-platform > bp-search > classes > class-bp-search.php file on line 519

**Support ticket links**
[https://secure.helpscout.net/conversation/1399373416/120463](https://secure.helpscout.net/conversation/1399373416/120463)

**Comment by mahedihasannoman** [comment]
https://github.com/buddyboss/buddyboss-platform/issues/2059

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
