### ISSUE TITLE
Having message notifications but when clicked it shows "No New Messages"

### ISSUE THREAD

**Issue by Santos-Jamie** [buddyboss/buddyboss-platform#2068]
**Describe the bug**
Users are having "Message Notification" but when clicked it shows "No New Messages"

**To Reproduce**
1. Go to BuddyBoss > Tools > Repair Community
2. Scroll down and look for "Reinstall emails"
3. Check the option then repair items

**Screenshots**
https://prnt.sc/xleffl

**Support ticket links**
https://secure.helpscout.net/conversation/1373466337/115899/
https://secure.helpscout.net/conversation/1387031256/118279/
https://secure.helpscout.net/conversation/1463114014/132471
https://secure.helpscout.net/conversation/1449236345/129869

**Comment by ToniicTech** [comment]
I am having the same issue and its a major complaint in our community as they want to use inbox notification to know they have messages but they have notifications when their inbox is empty

**Comment by sadrul** [comment]
@Santos-Jamie As you told the issue already been fixed, could you please cross check and close it.

**Comment by Santos-Jamie** [comment]
This issue has been fixed. Unread messages can now be repaired on repair community.

**Comment by ToniicTech** [comment]
Thanks for the update

Regards,

John


*John Berger, CFA*
Director: Operations & Impact Solutions
Toniic Institute <https://www.toniic.com/>
+1-904-325-4524

The global action community for deeper impact investing
www.toniic.com



IMPORTANT LEGAL INFORMATION - The choice to use and manner of utilization
of information and knowledge gained through Toniic is each investor’s
individual choice. Toniic does not recommend or otherwise suggest that any
investor invests in any financial product or that any fund manager offer
products to a particular investor. Investors should consult an investment,
tax and legal professional before deciding to invest in any financial
product. No guidance shall be given, nor shall any person or entity
affiliated with Toniic, or Toniic itself, be responsible for an individual
investor’s use of the information, investment decision, or the results of
any investment. Toniic takes no part in the negotiation or execution of a
transaction for the purchase or sale of financial product, and at no time
has possession of funds or financial products.  Toniic receives no
compensation in connection with the purchase of financial products. Toniic
is not a registered broker-dealer or investment adviser and signing onto
Toniic’s Gust platform does not guarantee an investment of any form.
