### ISSUE TITLE
When using the Search Activity bar, automate the load when deleting the terms

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#2073]
**Is your feature request related to a problem? Please describe.**
When a user enter terms in Activity Search bar and hit enter, they will be shown with the search results
But when they delete the terms, the activity feed does not load and you will need to hit enter on a blank search bar or reload the page

**Describe the solution you'd like**
When users delete the terms, the activity feed should load simultaneously

**Support ticket links**
https://secure.helpscout.net/conversation/1400222589/120581

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
