### ISSUE TITLE
Ability to sort the activity feed by "New Posts" and "Recent Activity"

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#2076]
**Is your feature request related to a problem? Please describe.**
For the moment, the activity feed is sorted in a chronological order (based on the creation date of the activity). But when someone like or comment a "old activity", that activity is not displayed at the top. Thus, it is hard/impossible to know what really happened since the last time.

**Describe the solution you'd like**
Facebook has 2 sort options : **New Posts** and **Recent Activity**.
![image](https://user-images.githubusercontent.com/46819762/105904973-291f3e00-6022-11eb-99b8-3fb093722096.png)

Add the ability to sort the activity feed based on "recent activities".

**Describe alternatives you've considered**
none

**Support ticket links**
none

**Comment by mrw** [comment]
Hi! We're looking for this feature also. Do you plan to incorporate it into the platform?

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
