### ISSUE TITLE
Replace autocomplete group name in "whats new" form with dropdown list

### ISSUE THREAD

**Issue by michalmaciak89** [buddyboss/buddyboss-platform#2091]
**Is your feature request related to a problem? Please describe.**

Users may not know specific group names.
It's not user friendly solution, dropdown list would be much better.

**Describe the solution you'd like**

Dropdown with a list of groups

**Comment by joarmnius** [comment]
1000% yes. It was a dropdown in the boss theme and SO MUCH better. It's now a pain to post when it could be so much straightforward

**Comment by marienel21** [comment]
Hi @michalmaciak89 ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
