### ISSUE TITLE
Option to force users to post to groups from "what's new" form in main activity feed

### ISSUE THREAD

**Issue by michalmaciak89** [buddyboss/buddyboss-platform#2092]
**Is your feature request related to a problem? Please describe.**
I would be nice to have option to disable "Post in: Profile" in the main activity feed and force users to use "Post in: Group" (to choose the right topic for their activities)

**Comment by joarmnius** [comment]
This one +++
There is a feature to not enable "connection between memebers" as a component BUT when this option is not enabled + You want to get relevant activity feed, nobody sees the updates post in profiles.

I built my community like a mighty netork more than a facebook. It's not centered on connection and each one profile but on community / groups. So it would be really really nice to allow to disable this "post in profile"

Thanks!

**Comment by marienel21** [comment]
Hi @michalmaciak89 ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
