### ISSUE TITLE
Issue with define( 'BP_ENABLE_MULTIBLOG', true );

### ISSUE THREAD

**Issue by alexlii1971** [buddyboss/buddyboss-platform#2095]
Hello,

Please check this plugin at https://buddydev.com/plugins/buddypress-multi-network/

It is recommended by Buddypress official site at https://codex.buddypress.org/getting-started/installation-in-wordpress-multisite/

Two issue in this situations:

1# No data imported after push "import demo data", but show critial Error.
2#No memebers show up in members directory page.

Would you please let me know how to resolve?

Thanks and have a nice day.

**Comment by marienel21** [comment]
Hi @alexlii1971,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
