### ISSUE TITLE
Clicking the users who like your post does nothing

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2110]
**Describe the bug**
Hovering the people who like the post seem to be clickable, but clicking it does nothing. 

**To Reproduce**
1. Post an activity.
2. Using other accounts, Like the post you just created.
3. Hover to the users who like your post, notice that it seems to be clickable but it does not do anything.

**Expected behavior**
Clicking the user who like your post should redirect to their profile.

**Screenshots**
![buddyboss](https://user-images.githubusercontent.com/58522498/106779703-38396800-6682-11eb-8e1a-8f14c6e8ec3b.jpg)
As reference, using the BuddyBoss Wall
![boss](https://user-images.githubusercontent.com/58522498/106779706-38d1fe80-6682-11eb-9351-2882c66614d2.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1412762010/122985

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
