### ISSUE TITLE
RTL: option to add Left to Right function in text area when RTL is activated

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#2119]
**Is your feature request related to a problem? Please describe.**
Capable to add new function in text area: https://prnt.sc/yg6phb when the site was in RTL mode.

**Describe the solution you'd like**
In backend function
Before:
https://prnt.sc/yg5g45
After
https://prnt.sc/yg5jb8

Screen Recording: 
https://secure.helpscout.net/conversation/1411906434/122871/

**Describe alternatives you've considered**
Doing the same function the backend is capable of changing the text position from RTL to LTR when RTL is activated.

**Support ticket links**
https://secure.helpscout.net/conversation/1411906434/122871

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
