### ISSUE TITLE
Allow multiple profile types for a single user

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#2120]
**Is your feature request related to a problem? Please describe.**
Allow users to select multiple profile types and have filters for it e.g. shortcodes to display 

**Support ticket links**
https://secure.helpscout.net/conversation/1409398409/122407

**Comment by ouch-digital** [comment]
+1

**Comment by Felipemauah** [comment]
+2

**Comment by stefan-glumpler** [comment]
That would be great! 👍

**Comment by marienel21** [comment]
Hi @emmanoctaviano ,

We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team

**Comment by MaxLynam** [comment]
this does not seem to be in the roadmap ?!?!?!?
