### ISSUE TITLE
Add a counter for the documents uploaded in Groups

### ISSUE THREAD

**Issue by RogelioBB** [buddyboss/buddyboss-platform#2158]
Please see screenshot https://prnt.sc/zxdf4m

**Comment by fabiomail** [comment]
The same should be done for "Discussions".

**Comment by marienel21** [comment]
Hi @RogelioBB,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
