### ISSUE TITLE
Reply author not notified

### ISSUE THREAD

**Issue by JeanDavidDaviet** [buddyboss/buddyboss-platform#2172]
https://github.com/buddyboss/buddyboss-platform/blob/32357edb19fd46a12a32897883a8ecfe3d2efbb2/src/bp-forums/notifications.php#L218

When I reply to a topic reply, the author of the original reply isn't notified, instead it is the author of the topic who is notified.

Should't `$args['secondary_item_id']` be replaced with `$args['user_id']`?

**Comment by marienel21** [comment]
Hi @JeanDavidDaviet,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
