### ISSUE TITLE
New Enhancement to the Relpy Post Modal view

### ISSUE THREAD

**Issue by chidiebereVendasta** [buddyboss/buddyboss-platform#2176]
The Users for our site often get frustrated a times while replying to a post.  The Reply feature covers part of the reply, which is not ideal for responding to all points of a question, for example? in the ScreenShot attached below

<img width="954" alt="Screen Shot 2021-02-24 at 10 03 40 AM" src="https://user-images.githubusercontent.com/78431597/109028696-ae305e00-7687-11eb-801f-7e6a9f092d3c.png">

Ideally, the Reply feature within a discussion thread should pop under the post you're replying to rather than over the whole page like a modal view

This will be a good feature to enhance for BuddyBoss. Our site is growing and the current feature is starting to get more complains

Let me know your input on this!

**Comment by marienel21** [comment]
Hi @chidiebereVendasta,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
