### ISSUE TITLE
Show the Photo Albums in the main photo directory

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2184]
**Is your feature request related to a problem? Please describe.**
There is a link to create an album on the main photos directory but there is no way to see them on the main photos directory. Currently, you will need to go to each of the profile pages to see the available photo albums.

**Support ticket links**
https://secure.helpscout.net/conversation/1432811307/126496

**Comment by marienel21** [comment]
Hi @ayron-paul ,

We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
