### ISSUE TITLE
Add GitHub to the list of social networks in the profile social networks field

### ISSUE THREAD

**Issue by othomasprime** [buddyboss/buddyboss-platform#2187]
**Is your feature request related to a problem? Please describe.**

We run two maker networks on BuddyBoss Pro, and increasingly our students and makers view their GitHub profile as a social/professional profile they would like listed alongside more traditional ones, like LinkedIn and Instagram.

**Describe the solution you'd like**

Please add GitHub as an available social network in the list of social networks that can be included as profile fields using the "Social Networks" field type for profiles.

**Describe alternatives you've considered**

Using the "website" field type, but it does not offer the same kind of elegant user experience.

GitHub logo artwork for rendering the field logo is freely available at:
https://fontawesome.com/icons/github?style=brands

Many thanks for considering it!

Oliver

**Comment by marienel21** [comment]
Hi @othomasprime ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
