### ISSUE TITLE
Search using multiple keywords in Activity Posts

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2202]
**Is your feature request related to a problem? Please describe.**
When searching in the WordPress Posts, you can use multiple keywords in any order, and only posts that contain all of those keywords will be included in the search result. But when using multiple keywords when searching for BuddyBoss Activity, it is treated as a single word or phrase causing some activities not to be included in the result.

**To reproduce**
1. Create a WordPress post. For this example, we will use the keywords "sample" and "BuddyBoss". https://i.ibb.co/Mcx7bY7/1.jpg
2. Try to search "sample BuddyBoss" in the Posts and notice that it will return the post we just created. https://i.ibb.co/ZzjjCQC/2.jpg
3. Go to BuddyBoss > Activity. You should be able to see the activity for the new blog post that contains the same keywords. https://i.ibb.co/j8MGPq3/3.jpg
4. Try to search "sample BuddyBoss" in the Activity and notice that it will not return any activity posts. https://i.ibb.co/jW3t9Lv/4.jpg

**Support ticket links**
https://secure.helpscout.net/conversation/1433107177/126540

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
