### ISSUE TITLE
Allow creating new discussion with only images or documents

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2211]
**Describe the solution you'd like**
Make the description optional

![discussin](https://user-images.githubusercontent.com/58522498/110039428-2aa7f880-7d7c-11eb-9e98-3dac69188611.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1443990636/128911

**Comment by marienel21** [comment]
Hi @ayron-paul ,

We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
