### ISSUE TITLE
Allow use of HTML tags in forum discussion and reply

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2215]
**Is your feature request related to a problem? Please describe.**
Some users are using HTML tags or sometimes copy-pasting from third party text editors in forum discussions and replies which causing for the HTML tags to be visible and not rendered on the front end

**Support ticket links**
https://secure.helpscout.net/conversation/1445201288/129121?folderId=3701263

**Comment by jrbuddyboss** [comment]
https://secure.helpscout.net/conversation/1447546533/129584

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
