### ISSUE TITLE
Div-Tag appears in discussion messages instead of empty line

### ISSUE THREAD

**Issue by us0906** [buddyboss/buddyboss-platform#2225]
Hello all,
on our buddyboss-powered side we are experiencing some strange behaviour regards formatting text in discussion boards.

I add a new discussion. 
The first line of the post is empty.
then in second line test
Add two empty lines.

Save that.

an <div></div>-Tag is shown instead of the empty line. Editing the post will not correct thet problem.

With some customers entered text is "decorated" with <font></font> tags all over the text - sometimes even in the middle of words.

Regards
Ulrich

**Comment by us0906** [comment]
problem occurs on safari, firefox, Chrome
(all current versions)

**Comment by marienel21** [comment]
Hi @us0906 

Thank you for adding this issue, however as per the [notes](https://github.com/buddyboss/buddyboss-platform#support), this repository is not suitable for support issues. I’m going to close this ticket but if the problem is still outstanding please submit a support request at your [BuddyBoss.com](https://www.buddyboss.com/) account.

Thanks,
Marienel - BuddyBoss Product Team
