### ISSUE TITLE
Make the LearnDash comment and reply activities in threaded view

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2228]
**Is your feature request related to a problem? Please describe.**
New comments and replies in LearnDash courses, lessons, and topics create a new activity for each instead of having it on the threaded view.

**Support ticket links**
https://secure.helpscout.net/conversation/1445810342/129226/

**Comment by marienel21** [comment]
Hi @ayron-paul ,

We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
