### ISSUE TITLE
Opengraph Data in url posts

### ISSUE THREAD

**Issue by brown7477** [buddyboss/buddyboss-platform#2232]
I think it is vital that you you add Opengraph support for posts with URLs.
The plain text urls do not look very inticing and the Timelines would look very much better with the Opengragh data being displayed.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by marienel21** [comment]
Hi @brown7477 ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
