### ISSUE TITLE
New Feature: Featured Function

### ISSUE THREAD

**Issue by ragnabnet** [buddyboss/buddyboss-platform#2241]
Hello, it's been a while i'm using buddyboss platform and so far i found a big problem for a making an active community using buddyboss.

The user experience in the buddyboss app and buddyboss platform are really passive. So the conversion of the engagement for our user is so little. It's all caused due to no function available for us to make a featured hot topics/discussion, hot forum, or hot issue. So people in our community doesn't know what's going on in the forum or what people in the community currently like, because there's no automation to make a posts that have the most like to be go up to the header of a activity page section or in a forum page or in the home page.

If we want to build a strong community. It's supposed to be having a featured post (for engagement purpose) or maybe we can make a featured courses that people like also (for selling purpose).
So far, people need to click here and there to just find something that good for them and it'll take a long time to search. That's why it's not engaging. So please make these "featured" function to be release as we know the success of instagram and reddit as a community right now because their platform are really focusing on their user engagement. Thank you!

**Comment by marienel21** [comment]
Hi @ragnabnet ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
