### ISSUE TITLE
Two words fail - add OR? while Buddyboss Global Search

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#2244]
**Is your feature request related to a problem? Please describe.**
Currently when someone who searches for one teacher name “Adams” – will return good results – but when they type “Adams Kenneth” or “Keneth Adams” it returns ‘nothing found’ –We would like to see if two or more words are entered in search box that is finds all results, even those that only match one word, (and match either of two) –

**Describe the solution you'd like**
When searching for "adams anderson" - it fails to bring up anything.
when searching for "adams" is works as expected; members with that word show up and the wordpress Page with staff that include that name. same with search for "anderson" - it shows the staff page and a members page - great!
but if you put "adams anderson" in the search box, it returns nothing - even if you hit enter and go to the wordpress search page.

**Describe alternatives you've considered**
 Maybe an option to run this with OR ? maybe that could fix.

**Support ticket links**
https://secure.helpscout.net/conversation/1452455266/130428?folderId=4265312
https://secure.helpscout.net/conversation/1452519664/130441?folderId=4265312
https://secure.helpscout.net/conversation/1451255151/130246?folderId=4265312

**Comment by marienel21** [comment]
Hi @shyamwp14,

We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
