### ISSUE TITLE
BB REST API - Group Members Endpoint : Add route to retrieve data of one single member of a group

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#2268]
**Is your feature request related to a problem? Please describe.**
For the moment, there's no way to retrieve (get_item) data for one single member of a group based on user_id.

![image](https://user-images.githubusercontent.com/46819762/112302663-9d313780-8c9b-11eb-97a1-e52ba87ce1c6.png)

**Describe the solution you'd like**
Could you implement the GET method for the endpoint _/groups/(?P<group_id>[\d]+)/members/(?P<user_id>[\d]+)_ ?

Add route "READABLE" in the file _class-bp-rest-group-membership-endpoint.php_

**Describe alternatives you've considered**
none

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
