### ISSUE TITLE
Ability to repost a shared post or share on a social media channels like FB, Linkedin, Whatsapp etc.

### ISSUE THREAD

**Issue by sidchauh** [buddyboss/buddyboss-platform#2285]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to share published posts either internally on the platform or outside of the platform on Social Media Channel. For a published post there is no way to repost as well. 

**Describe the solution you'd like**
I am using a plugin Social Media share plugin from Ultimately Solution and it works great however it just doesn't blended in the buddyboss platform. Buddyboss's native social share can provide a better user experience

**Describe alternatives you've considered**
Social Media Share using this plugin by Ultimately Social - https://www.ultimatelysocial.com/usm-premium/

**Support ticket links**
Ticket Number - 129502 (https://www.buddyboss.com/my-account/?conversation_id=1447055784)

**Comment by marienel21** [comment]
Hi @sidchauh,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
