### ISSUE TITLE
BB REST API - Group Endpoint : Add missing fields in response related to user rigths

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#2298]
**Is your feature request related to a problem? Please describe.**
The reponse of the REST API query `GET {{host}}/wp-json/buddyboss/v1/groups/18` contains some user rights fields but not all of them. 

For the moment, we only have can_post, create_media, create_document.

**Describe the solution you'd like**
Add those fields to the response (based on the website url : http://localhost/groups/<group_name>/admin/group-settings/) : 

- can_invite : send group invite
- create_albums (for medias)
- create_folders (for documents)
- can_send_group_message

**Describe alternatives you've considered**
none

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
