### ISSUE TITLE
BB REST API - Group Membership Endpoint : Set correct error message

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#2300]
**Is your feature request related to a problem? Please describe.**
Some error messages are not describing the situation of the error case.

For example, in the case "Special case for self-removal: don't allow if it'd leave a group with no admins." (line **773** in the file **class-bp-rest-group-membership-endpoint.php**).

**Describe the solution you'd like**
The correct message should be something like "_As you are the only organizer of this group, you cannot leave it. You can either delete the group or promote another member to be an organizer first and then leave the group._"

**Describe alternatives you've considered**
none

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
