### ISSUE TITLE
Repair Community - Rebuild Profile URLs

### ISSUE THREAD

**Issue by JasonBroderick** [buddyboss/buddyboss-platform#2304]
As profile URLs are automatically generated from WordPress usernames we really need a way to bulk repair the Members Profile URLs after we setup our community. If you have already registered users before using BuddyBoss and/or you use a different plugin to handle registration that automatically uses Email Address as Username.

**Problem - Email address as username causes the members email to be written into to their profile URL.** This means that all members email addresses are visible in the address bar, and easily scrape-able for any public community. You can't go backwards for users already registered even if you switch to using Nickname as username, all previously registered users have their email addresses permanently written into their URL.

**Privacy Concern & GDPR Issue
As this constitutes an nonconsensual disclosure of members sensitive private information this is a serious privacy issue and also a breach of GDPR.** As a BuddyBoss user I have no way to rectify this situation easily myself and the platform does not provide me with a solution. Whilst this issue probably only effects a small segment of users, it represents an urgent issue for those it does effect. The only solution currently is to switch all my registrations to using Nickname as Username and to update my database manually with a script for all previously registered users, neither of which is a good solution or easily achieved for the average user.

**Proposed Solution**

**1. Platform Profile URL Setting** - Add a platform setting to allow us to select the format of profile URLs. Allowing "Nickname" OR "Username" etc. This means I can continue to use email address as username in all my registration forms if I wish but all future registrations will build the urls from the new format I select.

**2. Repair Community - Rewrite Profile URLs** - After selecting the new format for profile urls from the settings we need the option to Repair Community to fix the previous URLs. I don't know how technically challenging this is but I just can't think of any other way to achieve it. It's a major problem for me in my community as for some others as you can see below.

**Discussions In Unofficial Community**
https://www.facebook.com/groups/buddyboss/permalink/1192061021228738/
https://www.facebook.com/groups/buddyboss/permalink/851717611929749/

**Comment by JasonBroderick** [comment]
Issue has been being discussed for at least a year within the BuddyBoss community but has been ongoing for over 7 years from within the BuddyPress bbPress community. Solutions discussed here: 

https://bbpress.org/forums/topic/user-profile-url-uses-the-username-can-that-be-changed/

**Comment by justinpatrickkeller** [comment]
A white paper with instructions on how to do this in the database would be great, assuming it's even possible. I've not yet dug through the DB on a dev site to start playing with it... but perhaps a plugin feature isn't needed if just some instructions on how to do this manually could be produced.

**Comment by nixsee** [comment]
I hope it is ok for me to add to this discussion here. Here are some other ways in which this is a problem for all sites, not just ones with legacy email usernames.

Given that a user's profile URL is not tied to their nickname, if someone changes their nickname, then another user could use that nickname in the future. That would be fine, except @mentions do not get updated.

example:
1. John Smith registers as @john and username John - profile url xyz.com/members/john
2. @john, gets mentioned by a friend, Jane, "Hey @john, look at this". This tag points to xyz.com/members/john
3. John Smith later decides to change his nickname to @johnsmith
4. Jane tags him again "hey @johnsmith". This points to xyz.com/members/john as well
5. John Jones now registers as @johnjones because the username John is already taken. xyz.com/members/johnjones is his profile url
6. John Jones now realizes that @john is available as a nickname and takes it
7. Jane now says to John Jones and John Smith, "Hey @john @johnsmith look at this"

There are now two different @john tags that point to different profiles - the first one to xyz.com/members/john, the second to xyz.com/members/johnjones. John Smith also has mentions to both @john and @johnsmith, both pointing to xyz.com/members/john. John Jones could have mentions to both @johnjones and @john. 

This scenario seems very plausible and problematic, and could be amplified even further by multiple nickname changes.

The proper solution, it seems to me, would be to link the user profile url to the nickname, rather than the username. If the nickname changes, the username can stay as-is (which fixes the above-mentioned username=email problems) and the profile url will match it. But the problem still remains with multiple @mentions pointing to the same page and same @mention pointing to different pages. It seems necessary to be able to retroactively change all existing @mentions to reflect the new nickname/url

So, in the scenario above, the original John would have all previous mentions show @johnsmith, which points to xyz.com/members/johnsmith

I suspect this is an extremely complicated task, so a quick-fix for new sites is to prevent users from changing nicknames altogether - perhaps some sort of toggle in the settings that can remove Nickname from the Edit Profile page.

**Comment by marienel21** [comment]
Hi @JasonBroderick ,

We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
