### ISSUE TITLE
Membergrid: latest activity + friends

### ISSUE THREAD

**Issue by brave-sites** [buddyboss/buddyboss-platform#2311]
**Is your feature request related to a problem? Please describe.**
In the membergrid, under the name of the member you see 'lastest activity + friends'. I've two issues: Issue 1. The styling is bad. Friends is directly behind latest activity. No styling, no space, no seperator. Issue 2. You can't edit this field: 2a. you can't edit the 'latest activity', which is to detailed now (one day and three hours ago, should be 'yesterday' or 'one day'. 2b. you can't show only the latest activity OR friends. When using CSS display none, both disapear. 2c. I want something else (a profile field, place of living using BPProfileLocationx) displayed here, but that isn't possible.

**Describe the solution you'd like**
Make this field editable. 

![Screenshot-22-1](https://user-images.githubusercontent.com/7854158/113728360-54936880-96f6-11eb-822c-c5ecf3386777.png)

**Support ticket links**
132404

**Comment by mikejyoung** [comment]
Hi @brave-sites

Thanks for submitting this idea to the public roadmap.

Some more great feedback for how we can improve member directories. When we have more information about improvements planned, we will add them to the public roadmap.  

I'm closing this issue here as part of our efforts to keep our GitHub repository focused on work that is ready for development.

Mike
BuddyBoss Product Manager
