### ISSUE TITLE
More visual look membergrid: make the grid easy editable

### ISSUE THREAD

**Issue by brave-sites** [buddyboss/buddyboss-platform#2312]
**Is your feature request related to a problem? Please describe.**
At this moment, it isn't possible to edit the way the membergrid (and group grids) looks. It would be great if that changes and if there would be a possibility to edit this in the settings (looks of buttons, profile picture height + width, friends, latest active, displaying other profile fields) or better, edit this using Elementor. I already did some of this using CSS, but I've trouble with the responsive mobile version now.. A pro theme like Buddyboss should really have this kind of options. The grid now looks 2000'ish...

**Describe the solution you'd like**
See above.. 
![Members (how it looks (1)](https://user-images.githubusercontent.com/7854158/113729325-3417de00-96f7-11eb-88e8-9bcdcfcb7eeb.png)
![Members (how I want it to look) (1)](https://user-images.githubusercontent.com/7854158/113729965-c15b3280-96f7-11eb-8aad-d1e59bf5cf97.png)

**Comment by mikejyoung** [comment]
Hi @brave-sites

Thanks for submitting this idea to the public roadmap.

We'll review your feedback when we're planning new features to extend the member's directory. When a new feature has been planned or is put under consideration, we will add it to the public roadmap.

I'm closing this issue here as part of our efforts to keep our GitHub repository focused on work that is ready for development.

Mike
BuddyBoss Product Manager
