### ISSUE TITLE
Editable accountsettings menu (option to add new menuitem + 'page')

### ISSUE THREAD

**Issue by brave-sites** [buddyboss/buddyboss-platform#2313]
**Is your feature request related to a problem? Please describe.**
I'm using memberpress and Modern Events Calender. I want to merge all of their 'setting pages' and display it all in the accountsettings of buddyboss/buddypress. Otherwise, you have settingpages all over the site.  

**Describe the solution you'd like**
It should be great if you can add a new menu-item + page, where you can drop a shortcode (and/or text). Now you have 'login information, e-mail preferences, privacy, group invites, export data'.

For example, it would be great if I can add:
1. a menu-item named: 'membership' with tabs like 'subscriptions' and 'payments' and add the MemberPress settings here. 
2. a menu-item named: 'events' with tabs like 'my events', 'rsvp's', 'privacy' and add the Modern Events Calender here (they are building a buddyboss group events add on which is coming soon)
3. a menu-item named: 'suggestions' where I can put a shortcode for a e-mailform 
4. a menu-item named 'how it works' where I can put (elementor styled? should be GREAT) information about how the site works and where you can find what..
 
![Knipsel](https://user-images.githubusercontent.com/7854158/113734228-7511f180-96fb-11eb-896b-e04b9c4cebf8.JPG)

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by mikejyoung** [comment]
Hi @brave-sites

Thanks for submitting this idea to the public roadmap.

We'll review your feedback when we're planning new features to improve the account settings area. When a new feature has been planned or is put under consideration, we will add it to the public roadmap.

I'm closing this issue here as part of our efforts to keep our GitHub repository focused on work that is ready for development.

Mike
BuddyBoss Product Manager
