### ISSUE TITLE
Profile fields groups as tab in profile

### ISSUE THREAD

**Issue by brave-sites** [buddyboss/buddyboss-platform#2314]
**Is your feature request related to a problem? Please describe.**
When you make different groups with profile tabs, they are all displayed UNDER each other instead of in menu-tabs. When you 'edit profile' they do are displayed as tabs. Only not on your profile.. I made many groups and profile tabs, so now my page is enormous, tabs would really be the solution. 

**Describe the solution you'd like**
See screenshot.

![Kni2psel](https://user-images.githubusercontent.com/7854158/113737137-0da97100-96fe-11eb-8f3a-7d2fa18e3158.JPG)

**Comment by mikejyoung** [comment]
Hi @brave-sites

Thanks for submitting this idea to the public roadmap.

We'll review your feedback when we're planning new features to improve member profiles. When a new feature has been planned or is put under consideration, we will add it to the public roadmap.

I'm closing this issue here as part of our efforts to keep our GitHub repository focused on work that is ready for development.

Mike
BuddyBoss Product Manager
