### ISSUE TITLE
More visual (2021) editable profilepage (elementor? settings?)

### ISSUE THREAD

**Issue by brave-sites** [buddyboss/buddyboss-platform#2315]
**Is your feature request related to a problem? Please describe.**
The buddyboss platform is a high end platform + theme, but you can't edit pages (profile, groups, overview of members and groups) visually without using lots of CSS. It would be great if you can edit some of the looks of the profile page, like displaying the profileheader site wide, a bigger profile photo, enable or disable some information, text (name etc) OVER the header instead of under, looks of the menu items. 

Just make the visuals a bit better/editable, a bit more 2021, without having to edit everything using CSS and breaking the responsiveness. (is that a word? ;-)) 

**Describe the solution you'd like**
Example of a more visual 2021 profilepage, could be a Buddyboss' profile page, when there would be some more options for the profile page.
![profile](https://user-images.githubusercontent.com/7854158/113746624-d25f7000-9706-11eb-8fca-ff6e626344fb.JPG)

How it's now
![profile now](https://user-images.githubusercontent.com/7854158/113746650-d7242400-9706-11eb-8e7b-8993b115a2e0.jpg)

**Comment by mikejyoung** [comment]
Hi @brave-sites 

Thanks for submitting this idea to the public roadmap.

We'll review your feedback when we're planning new features to improve the customisability of the BuddyBoss Theme. When a new feature has been planned or is put under consideration, we will add it to the public roadmap.

I'm closing this issue here as part of our efforts to keep our GitHub repository focused on work that is ready for development.
