### ISSUE TITLE
Add Widgets and Shortcodes to Gutenberg Blocks

### ISSUE THREAD

**Issue by deborah86** [buddyboss/buddyboss-platform#2335]
**Is your feature request related to a problem? Please describe.**

I am frustrated because Elementor received new blocks but there is nothing in Gutenberg with the same functionality even though on your website you claim to be compatible with Gutenberg.  This makes BuddyBoss useless for themes that don't have sidebars and block-based themes.  It will be even less compatible when full-site editing is introduced in WordPress. Not everyone wants to buy and use the BuddyBoss theme or Elementor.

Shortcodes are the only option but shortcodes don't allow you to edit settings as native blocks do.  Plus, there are not that many shortcodes available for use.  It is hard to pair shortcodes with Gutenberg blocks when designing a page.

**Describe the solution you'd like**

I would like to see all the widgets and shortcodes turned into native Gutenberg blocks.

**Describe alternatives you've considered**

I considered installing Elementor but decided against it because I didn't want to pay for a plugin I don't really need to use.

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by marienel21** [comment]
Hi @deborah86,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
