### ISSUE TITLE
Private repository for the students assignments to avoid copy-paste of assignments

### ISSUE THREAD

**Issue by Santos-Jamie** [buddyboss/buddyboss-platform#2338]
**Is your feature request related to a problem? Please describe.**
As of this moment, the admin are the only ones who can view the private documents upload on the media library but the Tutor/moderator can't review the docs if the students docs are private or set as only me. 

**Support ticket links**
https://secure.helpscout.net/conversation/1484255794/136453

**Comment by marienel21** [comment]
Hi @Santos-Jamie,

We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
