### ISSUE TITLE
Add custom tabs on the profile navigation

### ISSUE THREAD

**Issue by Santos-Jamie** [buddyboss/buddyboss-platform#2348]
**Is your feature request related to a problem? Please describe.**
Option to add custom tabs on the profile navigation to set as default tab

**Comment by marienel21** [comment]
Hi @Santos-Jamie,

We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
