### ISSUE TITLE
Long group descriptions poor UX on group pages

### ISSUE THREAD

**Issue by TokumeiJG** [buddyboss/buddyboss-platform#2357]
A user recently created their first group and added a really long description.

In the list of groups it is truncated (Screenshot2.png) but it is NOT shortened on any of the group pages (Screenshot.png).  This means users need to scroll past all of the description on each page of the group.  This is not a nice user experience.

Video:
https://www.loom.com/share/7b882c1e2c6543fdac96e3bf4ae59225

HOWEVER, it is reasonable for a user to add a long description describing the group, rules, purpose, contact etc.

I feel that group descriptions should be added as a tab called "About" or as a sidebar widget like in Reddit (ideally the group / site admin should be able to choose).

At the very least it should be an expandable div showing the first two likes and an option to expand it..

![Screenshot](https://user-images.githubusercontent.com/16894079/115638728-e41f5500-a34d-11eb-9eb6-45a7332f2b9c.png)
![Screenshot2](https://user-images.githubusercontent.com/16894079/115638740-e8e40900-a34d-11eb-8935-b2cb8d16d886.png)

**Comment by Gabrymi93** [comment]
+1 would be better to have a separated group tab or at least the "read more"

**Comment by marienel21** [comment]
Hi @TokumeiJG,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
