### ISSUE TITLE
Allow disabling of rich text editor in activity posts

### ISSUE THREAD

**Issue by bengrosser** [buddyboss/buddyboss-platform#2363]
I only want plain text entries in activity posts. In other words, I want to disable the rich text editing toolbar that allows bold, bullet lists, etc. I can hide it in CSS, but would be best if I could disable it altogether. I've looked through the code for a way to tweak but can't find it. 

If this is already an option, where is it?
If not, can this be added?

Finally, can anyone offer a temporary workaround to disable rich text editing in activity posts?

Already tried:
I tried setting `bbp_use_wp_editor` to false, but I think this option is maybe only for forums?

**Comment by marienel21** [comment]
Hi @bengrosser,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
