### ISSUE TITLE
Daily or Weekly discussion email digest 

### ISSUE THREAD

**Issue by Santos-Jamie** [buddyboss/buddyboss-platform#2375]
**Is your feature request related to a problem? Please describe.**
Forum discussion notifications can be set up to a daily or weekly digest rather than single messages whenever there is any action on a forum that you are following

**Support ticket links**
https://secure.helpscout.net/conversation/1500567611/139916

**Comment by marienel21** [comment]
Hi @Santos-Jamie,

We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
