### ISSUE TITLE
Set Profile Type based on Wordpress Role or MemberPress Membership

### ISSUE THREAD

**Issue by escservices** [buddyboss/buddyboss-platform#2391]
**Is your feature request related to a problem? Please describe.**
Kinda, we're using memberpress and we have a use case where members want to renew their membership online but don't want to be shown under the members page and don't want access to any buddyboss features.  Profile Types would probably solve the issue since you can hide a profile type from the directory, however, since we're using memberpress registration we can't have the appropriate profile type auto-set for that membership type. 

**Describe the solution you'd like**
Set profile type based on Wordpress Role or Memberpress Subscription.  

**Describe alternatives you've considered**
Currently, we're going to have to have users change that field themselves or have admins notified when they register and change the profile type for them.    Another potential solution would be a way to sync memberpress registration fields with buddyboss profile fields.   Currently, only the native Wordpress fields seem to sync.

**Comment by marienel21** [comment]
Hi @escservices ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
