### ISSUE TITLE
"View As" button - Impersonating other people?! major security issue

### ISSUE THREAD

**Issue by dorearendil** [buddyboss/buddyboss-platform#2395]
Hello,
I've been testing the free Buddyboss Platform with a few coworkers to decide whether BB might work for our community.

One thing that happened during this test, however, threw us off completely: as Wordpress admin, I was able to see a "View As" button on the profile of each registered member on the platform (see screenshot attached). And when I clicked that button... I automatically began impersonating that member! 

For example, if I clicked on that button while visiting Tom's profile, all my interactions would happen as if I were Tom (posting messages, etc.). No error (or even warning) message told me this would be happening. And then I couldn't switch back to my own account without first logging out (from Tom's account), and logging back into mine.

Another admin was able to do the same, and "warg into" just about any of us.

To be quite frank, this looked like such a massive security flaw in the code that we're unsure whether to even continue testing Buddyboss, not to mention purchasing the Pro plugin. But I thought I should report this here, just in case...

![Screenshot from 2021-05-03 16-49-54](https://user-images.githubusercontent.com/3090867/117857713-5a4c1300-b28d-11eb-9cda-2c775648daad.png)

**Comment by redmodd** [comment]
I'm not from the BuddyBoss team, however, being able to proxy in as a user like this is a pretty common feature.

**Comment by marienel21** [comment]
Hi @dorearendil,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
