### ISSUE TITLE
Profile type field on profile search 

### ISSUE THREAD

**Issue by Santos-Jamie** [buddyboss/buddyboss-platform#2403]
**Is your feature request related to a problem? Please describe.**
Profile type field on profile search for the filter to display on the filter result widget on members directory

**Support ticket links**
https://secure.helpscout.net/conversation/1512733420/142158

**Comment by marienel21** [comment]
Hi @Santos-Jamie 

We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel
BuddyBoss Product Team
