### ISSUE TITLE
Topic Merge and Reply Split issue with Forum

### ISSUE THREAD

**Issue by jitendrabanjara1991** [buddyboss/buddyboss-platform#2507]
**Describe the bug**
When we merge any one discussion to another then the child's reply does not set in the positions. Same for the split functionality.

**To Reproduce**
1. Go to Forum
2. Add discussion in the forum
3. Added reply with a child in the above created discussion
4. Add another discussion in the same forum
5. Added reply with a child in the above created discussion
6. Merge discussion and see the error - https://screencast-o-matic.com/watch/cr1DX7V11qX

**Expected behavior**
The sequence of reply should not be changed.

**Screenshots**
Merge -  https://screencast-o-matic.com/watch/cr1DX7V11qX
Split - https://screencast-o-matic.com/watch/cr1DX8V11q8

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Jira issue** : [PROD-801]

[PROD-801]: https://buddyboss.atlassian.net/browse/PROD-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by shyamwp14** [comment]
https://secure.helpscout.net/conversation/1531381070/145518?folderId=4265312

**Comment by marienel21** [comment]
I can't replicate this on demo

**Comment by mikejyoung** [comment]
@jitendrabanjara1991 Does this issue still exist?

**Comment by rmmehta** [comment]
Hello @mikejyoung I am able to replicate the issue. Here I have one question ,

If user add the replay on the forum post and we merge the discussion at that time sub replay work as separate post as it's work right now or work as a replay? Can you please confirm on this.

**Comment by mikejyoung** [comment]
@sourabhmatolia 
Could you answer @rmmehta's question?

**Comment by nickchomey** [comment]
In addition to this problem of flattening the nested replies from a merged topic, there are other problems with merging as well (and perhaps split, move etc..., but I have only tested merge). All of the problems stem from the fact that when you merge a topic, the meta_keys for the source topic and replies and destination topic don't get appropriately updated by the bbp_merge_topic_count() function. 

https://github.com/buddyboss/buddyboss-platform/blob/4917ba7452e7b8edefe73adec4f2c5660425caf8/src/bp-forums/topics/functions.php#L1471

The reason for the flattening of the source/merged topic's nested replies is that it appropriately gets a new _bbp_reply_to key as it is now a reply, however it points to itself rather than the destination topic. If you change this manually, the problem from the OP of this issue is resolved. 

However, there is another major related problem - the pagination on the destination topic is broken. For example, set the number of replies shown per topic to a low number, create two topics with some replies, and merge them. There is no pagination even though there are enough replies to surpass the limit. Also, the pagination at the bottom doesn't reflect the merged topics/replies.

See this video. 

https://user-images.githubusercontent.com/88559987/142716624-af7bf508-a799-406c-9e58-3d2c11b998a7.mp4

The culprit is that the destination topic's _bbp_parent_reply_count key doesn't get updated. If you change it manually to reflect the new replies, the problem is resolved. However, it is important to note that it should only be incremented by 1, because the source topic becomes the root parent reply, and all of the former parents replies become children replies. 

Moreover, the source/merged topic retains the following topic-specific meta_keys, even though it is now a reply. I'd imagine this could cause issues with some of the forum functions - they should all be deleted.
* _bbp_last_active_id
* _bbp_last_active_time
* _bbp_last_reply_id
* _bbp_parent_reply_count
* _bbp_reply_count
* _bbp_reply_count_hidden
* _bbp_voice_count

The following wp_posts columns aren't updated either. I don't know what consequence these have, but there's no reason they shouldn't be updated as well.
* guid - source-topic
* menu_order - source-topic and replies

Another contributing factor is Object Caching. After I manually change all of the above, if Redis is turned on, then none of it gets fixed. It is necessary to flush the cache in order to see the changes. 

A final, general, forum problem is that the reply count at the bottom of a discussion (e.g. "Viewing 1 - 4 of 5 replies) doesn't update unless you refresh the page. I assume some sort of AJAX could fix that.

I hope this gives you what you need to fix these problems - it seems to be that its pretty dire, as I don't know how it would be possible to retroactively fix any databases that have been corrupted by this. 

I haven't looked at split or move replies, but it is worth looking into it more deeply.

**Comment by hercivalbuddyboss** [comment]
https://secure.helpscout.net/conversation/1701567391/174577/

**Comment by bb-yudhisthir** [comment]
Issue is reproducible for merge : https://somup.com/crlti10SHC 
@jitendrabanjara1991 Can you please cross check again for split issue as I am unable to replicate it

**Comment by nickchomey** [comment]
@bb-yudhisthir I'm not sure what your video adds to this issue... It was already established that this is a problem, confirmed by others, and I FULLY diagnosed the root problems. All that is needed is for you guys to implement code changes as per my spec.

**Comment by nickchomey** [comment]
#3251 is related to this issue, and has been diagnosed above. Both could be merged and addressed at the same time through the suggested postmeta and object caching fixes
