### ISSUE TITLE
Mentioned "@" user is not showing in Receiver's Personal Tab

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#2546]
**Describe the bug**
When User1 mentions User2, the "@user2" mention is showing on User1 timeline but not on User2

**To Reproduce**
1. Make sure activity tabs is enabled
2. As User1, mention "@user2" in timeline
3. In User1 Profile feed, you can see this mention
4. In User2 Profile feed, you cannot see this mention unless you go to "Mentions" tab

**Expected behavior**
The mention should be showing on User2 Personal Feed as well.
If the TABS are DISABLED, this wont show at all.

**Screenshots**
User1 mentioning: https://snipboard.io/kjEwWC.jpg
User2 profile feed: https://snipboard.io/79cvMR.jpg
User2 mention feed: https://snipboard.io/lEKhnR.jpg

**Environment**
Tested both on client staging site and my dev site.
(used client site for SS)

**Support ticket links**
https://secure.helpscout.net/conversation/1528745577/144995

**Comment by imehedidev** [comment]
https://secure.helpscout.net/conversation/1571015017/153288

**Comment by meetmakadiya** [comment]
@emmanoctaviano 
cc: @mikejyoung @imehedidev 
1. Regarding mention showing on receiver personal feed so the personal tab is related to showing updates by the user not for some user tagging show in the personal tab because regarding mention we have already tab. 
2. If the TABS are DISABLED, this won't show at all. => this is not replicated on the latest version and please check the video for more details.
for more details check the video: https://www.loom.com/share/bcf0bbff84794aed8289d034c95aa851
Please let me know if I need to correct any mistakes or omissions

**Comment by jrbuddyboss** [comment]
https://secure.helpscout.net/conversation/1571015017/153288

**Comment by bb-yudhisthir** [comment]
@emmanoctaviano checked with the latest version:

1 If the tabs are disabled, its showing in the the user2 timeline
2 If the tabs are enabled, it will show in mentions but not in personal as the personal means those activity initiated by that member itself and its the correct behavior ( cross checked with the buddypress )

So, closing this issue
