### ISSUE TITLE
Video Directory page _ My group tab is appearing even after deactivating social group component.

### ISSUE THREAD

**Issue by mohit-buddyboss** [buddyboss/buddyboss-platform#2654]
**Describe the bug**
On deactivating social group component on videos directory page " My groups"  tab is appearing with wrong count of videos and videos also getting interchange between 3 tabs on this page.

**To Reproduce**
1. Go to Settings>Components>deactivate 'social group'
2. Go to Videos directory tab.
3. See mismatch and interchange of photos between tab, count is wrong and also 'My groups' tab is appearing.

**Expected behavior**
Group related video must not appear on Videos directory page, Count must be correct and 'My group' tab must not appear.

**Screenshots**
https://loom.com/share/f64bc527b0684fd09fa608e699ac36ad

**Environment**
Local server

**Support ticket links**
N/A internally reported by QA.

**Comment by surajkrsingh** [comment]
@mohit-buddyboss 
We found a similar issue with the **Photos directory page** also where  **My group** tab is appearing even after the social group component is deactivated.

The issue is reported by the customer - https://secure.helpscout.net/conversation/1582097398/155428?folderId=3709082
See this - https://tinyurl.com/yz4mu2k2

and I am also able to reproduce it on the local dev stage.
See this - https://www.awesomescreenshot.com/video/4634481?key=e708d547de82bc8d6594b6c565d96f27
