### ISSUE TITLE
Confused by Symbolic Links option for media

### ISSUE THREAD

**Issue by ianmjones** [buddyboss/buddyboss-platform#2657]
As a user I upload some photos to my profile, they are using the default symlink style of URL.

![Screenshot from 2021-07-21 17-38-35@2x](https://user-images.githubusercontent.com/4710/126527186-ce086e85-b227-495b-97b1-5391b7a97ee7.png)

![Screenshot from 2021-07-21 17-34-13@2x](https://user-images.githubusercontent.com/4710/126527239-3cba0f52-1006-4bcd-a87c-ecb218ecec29.png)

The "Media Security & Performance" section of the settings say this symlink method improves security and performance.

![Screenshot from 2021-07-21 17-40-56@2x](https://user-images.githubusercontent.com/4710/126527634-3697f8a7-a86f-4bc6-95f4-91db91ef4363.png)

1. Please can you explain how security is enhanced given that I can use the URLs in an incognito/private browser session that has never been logged into the site?

![Screenshot from 2021-07-21 17-41-51@2x](https://user-images.githubusercontent.com/4710/126527915-b0091cb1-11f1-46bd-9ffc-fdd65dd34a41.png)

2. And how are these symlinks more performant? That's a genuine question, would love to know.

**Comment by sourabhmatolia** [comment]
Hello @ianmjones 

> Please can you explain how security is enhanced given that I can use the URLs in an incognito/private browser session that has never been logged into the site?

It improves security because the Media file URL is unique which is only available to members with the right permissions.
IF member with the permission still wants to share Media file then they can, by Downloading Media, by Sharing URL, by Taking Screenshot, by Recording Screen, etc.
But it is secure to not allow other members to access media files without members with permissions.



> And how are these symlinks more performant? That's a genuine question, would love to know.

Previously we were loading all media files using Php script.
PHP Script used to load WordPress instance, check if a user is logged in, check if the user actually has permission to view specific media files, etc.
That impacts performance a lot when we render more than one media anywhere on the Network.
To solve this we came up with a Mechanism to generate unique string Symbolic URLs which will automatically purge after 24 hours and will be purged when Media permissions changed.

I hope that answers your questions.

IF you have more questions please reach out to us directly.
We will be happy to answer.

Closing this ticket for now. 

Thank you.
