### ISSUE TITLE
Group create activity is not visible on the activity even setting is selected.

### ISSUE THREAD

**Issue by kishanjasani** [buddyboss/buddyboss-platform#2675]
**Describe the bug**

Since platform and theme update 1.7,

When someone creates a new group there is not updated activity related to the group on the activity stream. It's set to post on the activity stream but for some reason, it's not. Was working prior to the latest update. But not sure if it has anything to do with the update.

 Also, every time I create a new lesson, topic, or quiz in Learndash, they are not being featured in the activity feed.

**To Reproduce**
1. Go to 'Group or Lessons'
2. Click on 'Create Group Or Lessons'
3. Publish the Group
4. See there is not any activity related to the group.

**Screenshots**
https://screencast-o-matic.com/watch/criOQNVi5cD

**Environment**
Demo site as well as client site

**Support ticket links**
https://secure.helpscout.net/conversation/1580555356/155151/
https://secure.helpscout.net/conversation/1580949308/155211/

**Comment by surajkrsingh** [comment]
@kishanjasani 
1. Creating a group from the frontend record the activity once we complete all steps.
Because creating activity feed for group needs privacy-status and these settings are in 2nd steps.

2. To create an activity for the Courses, lessons, topics and all needs to enable the settings 
from Buddyboss platform > Settings > Activity > Posts in Activity Feeds > enable the respective **Custom Post Types** 

@janakkaneriya007 please check and close the issue if the reason is valid.

**Comment by janakkaneriya007** [comment]
@kishanjasani 
Follow the steps suggested by @surajkrsingh above that will create an activity respectively. Once you confirm on your side you can close the issue.
