### ISSUE TITLE
Forum > topics pagination is not working

### ISSUE THREAD

**Issue by shyamgudadhe** [buddyboss/buddyboss-platform#2711]
**Describe the bug**
In Elementor page builder when insert Elementor Shortcode with  "[bbp-forum-index]", then pagination is not working.
This [bbp-forum-index] shordtcode is working with Add Block shortcode.

**To Reproduce**
1. Go to 'Elementor page'
2. Insert Elementor Shortcode and added "[bbp-forum-index]"
3. Forum topics Pagination is not working

**Expected behavior**
It should work after when [bbp-forum-index] use in Elementor Shortcode page builder.

**Screenshots**
https://www.loom.com/share/337055ce60a2498a93c2155b86a2e395

**Environment**
Dev site (https://dev-shyam.flywheelsites.com/)

**Support ticket links**
https://secure.helpscout.net/conversation/1573751911/153861?folderId=4265312

**Comment by surajkrsingh** [comment]
We have a similar issue on the demo site and customer end but happening on the forum page.
**Forum > all discussion pagination is not working.**

**Possible reason** - Because discussion pagination number has URL for the forum and when we click on no-2 it shows the next page forums but not the discussions. 

Here forum pagination and all discussion pagination numbers have the same URL. So, that it considers as a forum, not for discussion.
https://demos.buddyboss.com/online-communities/forums/page/2/
Demo - https://www.awesomescreenshot.com/video/4869001?key=06b70ca727ef6ab931f291e632bdcf7b

Customer issue ticket - https://secure.helpscout.net/conversation/1598980723/158317?folderId=3709082

**Comment by marienel21** [comment]
Similar issue reported here https://github.com/buddyboss/buddyboss-platform/issues/2646

**Comment by shyamwp14** [comment]
In Our Buddyboss community Formus page, All Discussions pagination is not working

https://demos.buddyboss.com/online-communities/forums/page/4/

https://www.loom.com/share/3767824f90184c1b8604b64bd2117c6c

https://secure.helpscout.net/conversation/1603875416/159204/

**Comment by marilyn9425** [comment]
https://secure.helpscout.net/conversation/1595160511/157642/

**Comment by furqanbb** [comment]
https://secure.helpscout.net/conversation/1616177550/161418/

**Comment by shyamgudadhe** [comment]
https://secure.helpscout.net/conversation/1621109579/162295/

**Comment by roshni07** [comment]
https://secure.helpscout.net/conversation/1608402012/159986/

**Comment by shyamgudadhe** [comment]
https://secure.helpscout.net/conversation/1620845031/162241/

**Comment by Shamina07** [comment]
https://secure.helpscout.net/conversation/1627974804/163505?folderId=3510499
