### ISSUE TITLE
Reporting an item sometimes creates duplicate records

### ISSUE THREAD

**Issue by janakkaneriya007** [buddyboss/buddyboss-platform#2724]
**Describe the bug**
When the moderation module is active and when we report items on the site, sometimes that will create duplicate entries on the backend as well DB.

**To Reproduce**
1. Go to the site
2. Report any item
3. Sometimes that will create two records in the backend as well as frontend

**Expected behavior**
It should only create one moderation record.

**Screenshots**
https://loom.com/share/7202dbe05f76424c8f4178696747accc

**Environment**
Which site did you replicate this issue on?

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by janakkaneriya007** [comment]
@mohit-buddyboss I have tried to replicate this issue but it's not getting replicated on my end. Can you verify on your end if you are able to reproduce this?

cc: @sourabhmatolia @firozwp

**Comment by mohit-buddyboss** [comment]
@janakkaneriya007 

I tried to replicate this issue but this issue is coming rarely and I'm not able to reproduce it again following the similar steps.
But this issue is coming randomly.  Screenshot : https://prnt.sc/1qs5nry

It do not replicate with similar steps every time but it occurs only when user report photos/doc/video from directory pages. When No reporting content is available. On fresh set up or after Truncating the moderation database. This issue will generate in this scenario but it is also random and will not happen each time. Let me know if you have any query.

cc @sourabhmatolia @KartikSuthar

**Comment by janakkaneriya007** [comment]
@mohit-buddyboss Followed the same steps but was not able to replicate the issue.

@sourabhmatolia @firozwp Need your thoughts here.
