### ISSUE TITLE
There are some warning when login to the site 

### ISSUE THREAD

**Issue by Shamina07** [buddyboss/buddyboss-platform#2850]
**Describe the bug**

There are some warnings on the console while login

**To Reproduce**

1. Go to '.Dev environment'
2. Login with the console open
4. See warning

**Expected behavior**
There should not be any warning 

**video**
https://share.vidyard.com/watch/kvVPeMVTSeZE7CdT6KhJq6?

**Environment**
I get it on the development environment 

**Support ticket links**
https://secure.helpscout.net/conversation/1609465006/0/?folderId=4687016

**Comment by rmmehta** [comment]
Hello @Shamina07 ,

This issue is resolved with the latest release I am not able to replicate the issue on my dev site as well as on client dev site.

Please see the screen shot for the same.

![client_ss](https://user-images.githubusercontent.com/82605214/134493703-4e95070d-5714-407b-827b-346f660ca479.png)

So, I have closed this issue.

Thanks,
