### ISSUE TITLE
Message Block member popup and member listing UI changes

### ISSUE THREAD

**Issue by amincdev** [buddyboss/buddyboss-platform#2875]
**Describe the bug**

1. Load more members link in the recipient list looks bad: https://prnt.sc/1qvtxz4
2. Messages > Group Thread > Block Member Popup > we should not show blocked or suspended members in the list.

**To Reproduce**
1. Go to Message
2. Create a thread with more than 20 members
3. See error

**Screenshots**
https://prnt.sc/1qvtxz4

**Comment by jitendrabanjara1991** [comment]
@sourabhmatolia 
Regarding this - **Messages > Group Thread > Block Member Popup > we should not show blocked or suspended members in the list.** - Based on my checking its looks like new enhancement not a bug. I have checked on plugin version 1.7.5 and its also showing **Blocked Member** in block member list.
Based on solution I need to pass two diff object in ajax, based on that I can display member list. For ex - Please check  attached screenshot.
![image](https://user-images.githubusercontent.com/30429982/132357877-8d21b7b9-6e9e-4d14-9741-941f6bcfc23b.png)

So, Please confirm to me this way is fine. Because I think if I change this then also check for API. Because In APP, **Blocked Member**  is displaying.

cc - @chetansatasiya @KartikSuthar 
Thanks.

**Comment by sourabhmatolia** [comment]
@jitendrabanjara1991 

Yeah, I realize it was like this before also, and it is not a bug from the last update.
But we still need to fix that.

Whenever we are seeing a list of members or member content anywhere then we don't show suspended members, Blocked members, and we don't show their generated content also.
Reason we are showing in the message, forum reply, activity comment, post comment because there is a back and forth discussion ongoing. Everywhere else we don't show.
Similarly, we need to hide in that block popup.

So yeah looks like you will need to pass two diff object in ajax. If the same needs to be changed in the API also please do. 

Thanks.

**Comment by shakilAshraful** [comment]
Note: This doesn't since the app implements a different design for message recipients.

![Screenshot 2021-09-08 at 3 56 49 PM](https://user-images.githubusercontent.com/64884320/132488959-83a516fb-de3f-4c3c-8df9-c9cfd9b3f307.png)
