### ISSUE TITLE
Multisite Profile Sites Tab and Setup Process

### ISSUE THREAD

**Issue by tyranthacker** [buddyboss/buddyboss-platform#2896]
I seen some dated issues from last year and it looks like maybe they were fixed?

On a sandbox, I have Multisite, WP Ultimo, and BuddyBoss Platform + Pro using the BuddyBoss Theme.
--BuddyBoss Platform + Pro are installed on a sub-site. 
--On this sub-site, on a users profile it shows the Sites tab, but the listed sites don't seem to be syncing/ updating. (it does show some sites, but new ones added are not showing up..)

I have attempted to replicate the issue or test it, but on other installs I can't even get the Sites tab to show up. 
I have looked for proper documentation on how to setup BuddyBoss and Multisite and can't seem to find a clear process.

Do you network activate BuddyBoss?
Do you only activate it on the Main Site?
Can you activate it on One sub-site and not the main site?

We really just want to have BuddyBoss activated on One site that serves all our sub-sites.
Can we do this on a subsite instead of our main site? 

**Jira issue** : [PROD-745]

[PROD-745]: https://buddyboss.atlassian.net/browse/PROD-745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by gastronimo** [comment]
"We really just want to have BuddyBoss activated on One site that serves all our sub-sites.
Can we do this on a subsite instead of our main site?"

Same issue as?:
https://github.com/buddyboss/buddyboss-platform/issues/2815#issuecomment-908361598
https://github.com/buddyboss/buddyboss-platform/issues/2896
https://github.com/buddyboss/buddyboss-platform/issues/2873
