### ISSUE TITLE
Video thumbnail issue with portrait video

### ISSUE THREAD

**Issue by amincdev** [buddyboss/buddyboss-platform#3063]
**Describe the bug**
When uploading a portrait video, auto-generated thumbnail does not proper while uploading a video. Also, after uploading video server-generated thumbnails are stretched.

**To Reproduce**
1. Go to activity
2. Upload potrait video
3. See auto generated image: https://prnt.sc/1w2vbog
4. Also after uploading, go to video -> Change Thumbnail option. See, auto-generated thumbnails are stretched: https://prnt.sc/1w2vrjx, https://prnt.sc/1w2vtdz

**Expected behavior**
Thumbnails should be seen proper when portrait video is uploaded

**Screenshots**
 https://prnt.sc/1w2vbog, https://prnt.sc/1w2vrjx, https://prnt.sc/1w2vtdz

**Jira issue** : [PROD-719]

[PROD-719]: https://buddyboss.atlassian.net/browse/PROD-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sourabhmatolia** [comment]
**Adding my comment as it is so that we don't miss any points:**

- Doesn’t work fine while uploading portrait video: https://prnt.sc/1w2vbog
- Works fine after posting: https://prnt.sc/1w2vdi5
- Change thumbnail Popup shows auto-generated images also wrong: https://prnt.sc/1w2vh2c and https://prnt.sc/1w2vrjx
- When you change thumbnail using an auto-generated one then it looks stretched: https://prnt.sc/1w2vtdz
