### ISSUE TITLE
Text format is being removed when pasting it in compose message or activity

### ISSUE THREAD

**Issue by kent-carlo** [buddyboss/buddyboss-platform#3066]
**Describe the bug**
Text format is being removed when you copy it and paste in compose a message or compose activity. The issue only happens in version 1.7.7 and above.

**To Reproduce**
1. Copy any random text with format e.g. with break line at least.
2. Paste it in compose a message or activity.
3. You'll see that it will only paste as plain text and even the break line doesn't get included.

**Expected behavior**
Text formatting should get included when pasting.

**Screenshots**
https://www.loom.com/share/3d7146c87d464fc089840f2b5c8f1f8f

**Environment**
Which site did you replicate this issue on? 
Demo site

**Support ticket links**
https://secure.helpscout.net/conversation/1645273046/166328?folderId=3709082

**Jira issue** : [PROD-718]

[PROD-718]: https://buddyboss.atlassian.net/browse/PROD-718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Santos-Jamie** [comment]
https://secure.helpscout.net/conversation/1676520143/170948

**Comment by milanhirapra** [comment]
There are two issue regarding text format issue:
1) https://github.com/buddyboss/buddyboss-platform/issues/1688
2) https://github.com/buddyboss/buddyboss-platform/issues/3066

As I checked #1688 issue, it is not valid issue because if we paste any text with HTML tag then editor will not convert in formatted text. Therefore, I reverted #2699 PR in this(#3066) issue.

CC: @KartikSuthar @chetansatasiya @sourabhmatolia

**Comment by surajkrsingh** [comment]
https://secure.helpscout.net/conversation/1652973437/167598?folderId=4687016

**Comment by Santos-Jamie** [comment]
https://secure.helpscout.net/conversation/1701192231/174530/
