### ISSUE TITLE
Forums that are not connected to groups are changing all the pagination of the displayed forum

### ISSUE THREAD

**Issue by Santos-Jamie** [buddyboss/buddyboss-platform#3087]
**Describe the bug**
When you go to page 2 of a forum that is not connected to groups, it also changes all the forums page

**To Reproduce**
1. Create new page
2. Edit using Elementor and use the short code widget
3. Use the shortcode [bbp-single-forum id=$forum_id] and display a forum that is not connected to any groups
4. Display another forum that is connected to groups
5. Save changes
6. Go to page 2

**Screenshots**
https://www.awesomescreenshot.com/video/6408163?key=57b229f36cad85208b3c37103f3a8be4

**Environment**
Demo

**Support ticket links**
https://secure.helpscout.net/conversation/1652311990/167465

**Comment by surajkrsingh** [comment]
@Santos-Jamie 
I checked the issue and found using 2 shortcodes on a single page will lead to that issue, not actually an issue but it is the way to work for the pagination.

**See this video** - https://www.loom.com/share/abfb7dc2d9094619b4d94460b5813440

I don't think so that required a fix because pagination works on page level and it will load the page as the URL get the number ( it doesn't matter which and how many forums you are using)

Please check and let me know if still have any questions.

**Comment by Santos-Jamie** [comment]
Hi @surajkrsingh this is noted. I will explain the following to the client. Thank you for checking
