### ISSUE TITLE
Global search return zero count for custom CPT's/search types

### ISSUE THREAD

**Issue by 1naveengiri** [buddyboss/buddyboss-platform#3505]
**Describe the bug**
Global search results show zero counts for custom CPT's search results.

I checked the code and found you are using a variable `$cache_key` to maintain the total post count of different CPTs or search types. 
https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-search/classes/class-bp-search-types.php#L94

if this variable is set once to zero, it will always return a zero result count for proceeding CPTs or search types. 

and causes the problem where even though results are found the count is always zero. 
<img width="1322" alt="Screenshot 2022-06-02 at 7 37 07 PM" src="https://user-images.githubusercontent.com/24760592/171648072-6c506236-469a-4bdd-af83-d967e00beb8a.png">

**To Reproduce**
1. activate the global search
2. add the Geodirectory plugin  or you can use CPT-UI
3. add some posts in the GD CPT 
4. search for the posts 

**Expected behavior**
the $cache_key variable name should be unique. 
**Example: **  https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-search/classes/class-bp-search-posts.php#L313
`'bb_search_term_total_match_count_' . sanitize_title( $search_term )` to `'bb_search_term_total_match_count_' . $post_type . '_' . sanitize_title( $search_term )`

or add one more condition here
https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-search/classes/class-bp-search-types.php#L95

`if ( ! isset( $bbp_search_term[ $cache_key ] ) || empty( $bbp_search_term[ $cache_key ] ) ) `

**Comment by mahedihasannoman** [comment]
Hi @1naveengiri ,
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
FYI, This issue is already in our sprint and it is currently ready for production.
Thanks.

**Comment by 1naveengiri** [comment]
Good to hear that ... Cheers.
