### ISSUE TITLE
Crittical wordpress error while goind to forums main page

### ISSUE THREAD

**Issue by anoykin** [buddyboss/buddyboss-platform#3517]
when I activate the Forums component and go to the forums main page, I get a crittical 
![Image 208](https://user-images.githubusercontent.com/66867558/174298262-e3471519-e33f-4db7-806a-103df65cf0ea.png)
![Image 209](https://user-images.githubusercontent.com/66867558/174298275-1a24f89f-227d-43b7-853c-1c92a658357b.png)
![Image 210](https://user-images.githubusercontent.com/66867558/174298283-0ee73bed-27e9-4f7e-894b-35b9769c1dc7.png)
![Image 211](https://user-images.githubusercontent.com/66867558/174298290-237d1bba-30e5-4e17-b92a-38982f7ec991.png)
![Image 212](https://user-images.githubusercontent.com/66867558/174298294-69bb1e27-2e85-46e6-8900-869b2a545f78.png)
![Image 213](https://user-images.githubusercontent.com/66867558/174298302-f70a9271-35ef-4c1d-86a3-77223dc880d5.png)
![Image 214](https://user-images.githubusercontent.com/66867558/174298310-9ed94a10-3aef-47ea-9c60-20cb03a202fa.png)
![Image 215](https://user-images.githubusercontent.com/66867558/174298319-e0bca053-bd10-4888-bb37-c348d37a932f.png)
error. Site bitmejkerskaya.ru/forums-3

Screenshots of settings pages:

**Comment by bb-yudhisthir** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
FYI, This issue is already in our sprint and it is currently ready for production.
