### ISSUE TITLE
[android upload error] Your app is currently targeting API level 30. Targeting to at least API level 31 is required to ensure that it is based on the latest APIs, optimized for security and optimal performance. You need to change the focus level of the API in the application to at least level 31. Learn more

### ISSUE THREAD

**Issue by idanlevi1** [buddyboss/buddyboss-platform#3592]
I try to upload android `aab` file to the google play console (I generated release version and download it from the Buddyboss platform) 
and I get this error with this message:
`Your app is currently targeting API level 30. Targeting to at least API level 31 is required to ensure that it is based on the latest APIs, optimized for security and optimal performance. You need to change the focus level of the API in the application to at least level 31. [Learn more](https://developer.android.com/google/play/requirements/target-sdk)`

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/21155847/183463969-df9148d4-4df1-4732-9528-d0844eb36dd8.png">

Can I change the android API level? or there is another way to solve this error?

**Comment by meetmakadiya** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
FYI, This issue is already in our sprint.

https://buddyboss.atlassian.net/browse/PROD-3376
