### ISSUE TITLE
At members screen user is not able to search the particular user.

### ISSUE THREAD

**Issue by Ravinder-qa** [buddyboss/buddyboss-platform#402]
**Description**
When user search a member with space in his/her user name then that member is not appearing.
"No result found " showing
eg: like a member name is Ankit gupta and user search with full then that member is not showing. And when user search with only Ankit then result showing. So, please have a look into it

**To Reproduce**
Artifact:
https://www.loom.com/share/12e89ac46c6b43daa3fec07cb6bcb062

**Expected behavior**
User should be able to search particular user at members screen.

**Jira issue** : [PROD-958]

[PROD-958]: https://buddyboss.atlassian.net/browse/PROD-958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by milanhirapra** [comment]
This is not a bug because if the **nickname** is **bb-charles(with the hyphen)** and the same value is stored in the database. So, if you are trying to search wih this string **bb charles(with space)** the query will be made like this **SELECT * FROM TBL_NAME WHERE FIELD LIKE '%bb charles%'** and the query will return null results because of the database table column is stored this value **bb-charles**.
