### ISSUE TITLE
Multiple Duplicate Profile Fields

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#495]
**Describe the bug**
When Migrating from Boss Theme/BuddyPress to BuddyBoss Platform thousands or multiple nickname, first & last name fields are creating. Also if you try to Repair via BuddyBoss > Tools > Repair Community > Repair default profile set and fields nothings worked.

**Expected behavior**
It should not create multiple nickname, first & last name fields .

**Support ticket links**
https://secure.helpscout.net/conversation/1112131418/14212/

**Comment by chetansatasiya** [comment]
At this moment closing this issue because we can't reproduce since long.

**Comment by StefanB997** [comment]
Hey, we moved from Social Learner (Buddy Press) to Buddy Boss platform few weeks ago and the same thing happened too. We did update the theme since but the problem still persists. It's kinda bad to require the users to fill out their name, lastname and nickname x10 times in order to complete their profile. Any advice on how to fix it?
