### ISSUE TITLE
Needs non-admin users permissions to modify or delete their discussion and replies.

### ISSUE THREAD

**Issue by yagom** [buddyboss/buddyboss-platform#612]
**Is your feature request related to a problem? Please describe.**
Non-admin users can only reply in forum discussion. They need more permissions.

**Describe the solution you'd like**
Give more permissions to non-admin user to edit - Edit, Move, Split, Trash, Close.. etc - their topics.
Also admin can control their permissions.

**Describe alternatives you've considered**
Nope...

**Support ticket links**
#62997

**Comment by bstreet123456789** [comment]
Yes please. This gives some important abilities to manage content which breaches website terms and conditions and can be managed and removed quickly.

**Comment by marienel21** [comment]
Hi @ouch-digital ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
