### ISSUE TITLE
Needs options to filter the forum in the forum archive list(or page)

### ISSUE THREAD

**Issue by yagom** [buddyboss/buddyboss-platform#613]
**Is your feature request related to a problem? Please describe.**
The forum archive page - a.k.a. /forums - lists all forums. But I want to reveal forum that set as public.
Shortly I want a option to hide non-public forums in forums archive page.

**Describe the solution you'd like**
Give options to filter forums in Settings - Forums

**Describe alternatives you've considered**
- Make short code - [bbp-forum-index] - parameters to filter forums.
- Seperate visibility option between Group and Group Forum

> Because I want to hide private forum(Private group's forum) from forum archive list.

**Support ticket links**
#62988

**Comment by marienel21** [comment]
Hi @yagom,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
