### ISSUE TITLE
Hide and protect messages uploads from search engines and crawlers

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#668]
Could you move uploads for messages from `wp-content/uploads` folder to `wp-content/uploads/messages` (or `bb_messages` for example). 
Then I could hide and protect this directory from search engines with using `robots.txt` and `.htaccess` files and this rule:
`Disallow: /wp-content/uploads/bb_messages/`

And another one recommendation:

Could you add file name randomization (for security).
Example:
Before: `https://test.site/wp-content/uploads/coffee.jpg`
After: `https://test.site/wp-content/uploads/bb_messages/lkjhgyukvftyui3iu278hfsdufh8.jpg`

**Reason:** It is not secure to put personal images in a public folder with public names. Anyone can find them in search engines or pick up a filename.

For example the same logic (folder and randomization) is working in this plugin: https://wordpress.org/plugins/bp-better-messages/
Related: https://wordpress.org/support/topic/files-directory-and-php-7-1-support/

Related: #987

**Comment by eisenwasser** [comment]
@AiratHalitov Thanks for the suggestions, we will consider these.

**Comment by marienel21** [comment]
Hi @AiratHalitov,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
