### ISSUE TITLE
Vimeo video does not have a play button when the course is just started. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#673]
**Describe the bug**
When the course is just started and the lesson is not marked as complete, some Vimeo videos do not display with play buttons. 

**To Reproduce**
1. Go to lessons page > add a video link in video progression tab
2. Check this for the courses just started and not marked as complete
3. check this for the courses marked as completed

**Expected behavior**
Video play button should be displayed for all the videos regardless of their status. 

**Screenshots**
- https://i.imgur.com/7lrhCC0.jpg
- https://i.imgur.com/9S2k7br.jpg
- https://i.imgur.com/iEncyA3.jpg
- https://i.imgur.com/g3GuzuH.jpg

**Support ticket links**
- https://secure.helpscout.net/conversation/1114695035/63613?folderId=3701247

**Comment by chetansatasiya** [comment]
@archanabb @eisenwasser 

I checked this issue and this is not a related to BuddyBooss Theme OR BuddyBoss Platform issue. I am facing the same issue by disabling all the plugins except learndash and enabling the WordPress default theme.

So, this issue is releated to Learndash plugin and that needs to report in Learndash plugin support.

**Comment by chetansatasiya** [comment]
@archanabb @eisenwasser 

To fix this issue temprary until Learndash Team fix If we enable this https://prnt.sc/rmfe5y option bydefault then it will start video once the page load.
