### ISSUE TITLE
How can i build a custom profile with course progression and learndash stuff?

### ISSUE THREAD

**Issue by hcmendez** [buddyboss/buddyboss-platform#763]
I want to make an online learning platform with social groups for classrooms and private classes and i need to make a custom profile template showing courses enrollment, progression, certificates and learndash stuff. And with the addon instructor role i want to add info about course i created, buttons to create courses and that kind of stuff.

**Comment by eisenwasser** [comment]
@hcmendez 

This is more of a custom work request rather than an "issue" (bug) in the platform, so I am going to close this issue here. Github is just for cataloguing bugs in the product.
https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Issues

Please submit this as a support request at BuddyBoss.com in your account there.

Much of what you are asking for would require some custom development. But do keep in mind that we have out of the box, a template on Profiles for displaying the users courses and certificates. https://youtu.be/Bs1UA1GulII

Thanks!
