### ISSUE TITLE
Enabling Post Comments in Activity causes the comments on Blog Posts not to be included in Activity feed

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#784]
**Describe the bug**
In BuddyBoss > Settings > Activity > Post Comments >  Allow activity stream commenting on blog posts, forum discussions and replies, enabling this option would add the comment option on forum replies and discussions on Activity feed but this also removes the functionality of Comments in Blog Posts to be generated on the activity page 

**To Reproduce**
1. In BuddyBoss > Settings > Activity > Post Comments >  Allow activity stream commenting on blog posts, forum discussions and replies = disable this option
2. Go to a single blog post and try to comment on post (make sure comments are allowed on blog post)
3. Go to activity feed, see your comment displayed on the activity feed
4. Go back to BuddyBoss > Settings > Activity > Post Comments >  Allow activity stream commenting on blog posts, forum discussions and replies = enable this option
5. Go again to single post and comment something
6. In activity feed, your comment is not displayed

**Expected behavior**
The comments on blog post should be available and this must have an own option if it were to be shown on activity feed.

**Screenshots**
https://drive.google.com/open?id=1fl718ueo9spQv-nrxk_ypIa-Jmz0lOIS

**Support ticket links**
https://secure.helpscout.net/conversation/1141825944/69710?folderId=3701258

**Comment by manishpatolia** [comment]
@emmanoctaviano 
I have checked but I seem working fine for me see the proof and let me know if I followed any wrong step. 
https://www.loom.com/share/f547067f5a444929ac007b91e5a189b9

When "Post Comments" Enable that time when we comment on the blog post that will go under in that post activities comments.
Otherwise, it will add as a separate activity.


"

**Comment by emmanoctaviano** [comment]
@manishpatolia please watch this https://drive.google.com/open?id=1dhxxWTH8ZlRS70I3jX2qBpjKVBwSLvBv this is still experienced on demo

**Comment by manishpatolia** [comment]
@emmanoctaviano This is not an issue please see my video it is working fine.

When "Post Comments" Enable then comment will be added as a comment on that blog post activities.
Otherwise, it will add as a separate activity.
https://www.loom.com/share/f547067f5a444929ac007b91e5a189b9

@chetansatasiya can give your thoughts here for this?

**Comment by emmanoctaviano** [comment]
https://secure.helpscout.net/conversation/1162989264/73180?folderId=3701258

**Comment by emmanoctaviano** [comment]
@manishpatolia have you tried testing on demo? we have more clients experiencing this.

**Comment by contemplate** [comment]
@emmanoctaviano  was this ever resolved for you?  It seems that when this setting is enable comments that are left on the post do not sync to the Activity feed.

**Comment by dlv2372** [comment]
I can't see any replies to posts on my feed, I'm not sure how you even achieved that in your video.

On top of that, blog post related "activities" in the feed do not have reactions/likes/gifs and so on, like other "activities".
