### ISSUE TITLE
The BBPress voting plugin does not work with Buddyboss

### ISSUE THREAD

**Issue by ZiadJ** [buddyboss/buddyboss-platform#786]
Is there a chance that this plugin can be made to work with the platform? Here is a thread confirming that it's not the case:  [http://wordpress.org/support/topic/not-working-with-buddyboss
](http://wordpress.org/support/topic/not-working-with-buddyboss
)

**Comment by ZiadJ** [comment]
The plugin relies on the following hooks to render the vote buttons but none of them are being called on forum pages so it seems like the action names are not registered in Buddyboss:
```
add_action('bbp_theme_before_topic_title', 'bbp_voting_buttons');
add_action('bbp_template_before_lead_topic', 'bbp_voting_buttons');
add_action('bbp_theme_before_topic_author_details', 'bbp_voting_buttons');
add_action('bbp_theme_before_reply_author_details', 'bbp_voting_buttons');
```
If that's the case then equivalent action names in Buddyboss that needs to be used instead?

**Comment by natekinkead** [comment]
Hey, just to update you on this.  A while ago, I updated my bbPress Voting plugin to work with BuddyBoss.  The plugin is now using these hooks for displaying the buttons and it seems to be working...

add_action('bbp_theme_before_topic_title', 'bbp_voting_buttons');
add_action('bbp_theme_before_topic_content', 'bbp_voting_buttons');
add_action('bbp_theme_before_reply_content', 'bbp_voting_buttons');

**Comment by marienel21** [comment]
Hi @ZiadJ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
