### ISSUE TITLE
Allow "Likes" in Activity > Comments/Replies

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#848]
**Describe the bug**
Allow "Like" functionality in Activity > Replies.
This is existing on BuddyBoss Wall with Boss Theme.

**To Reproduce**
1. Go to Activity, post something
2. Comment something to that post
3. You can only see Reply and Delete, but no Like option

**Expected behavior**
In BuddyBoss Wall, users have the option to Like the comments and replies on activity feed.
This must be existing on BuddyBoss  Platform as well.

**Screenshots**
![oldtheme](https://user-images.githubusercontent.com/58522224/81011350-62a78c00-8e8a-11ea-9e93-61456af1e0e3.JPG)
![newtheme](https://user-images.githubusercontent.com/58522224/81011424-87036880-8e8a-11ea-94f9-16c05e53bfe7.JPG)

**Support ticket links**
https://secure.helpscout.net/conversation/1148788883/70864?folderId=3701241
https://secure.helpscout.net/conversation/1148788883/70864/

**Comment by Anve-sri** [comment]
https://secure.helpscout.net/conversation/1207622411/80330

**Comment by Fl0rent** [comment]
Do you know if this improvement is still in development?

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel - BuddyBoss Product Team
