### ISSUE TITLE
BuddyBoss Business Pages - New Component

### ISSUE THREAD

**Issue by bryanr18lowe** [buddyboss/buddyboss-platform#849]
**Is your feature request related to a problem? Please describe.**
The ability to add a business page is vital for many community business models to be able to create valuable monetization verticals and fully capitalize on their community activity. 

**Describe the solution you'd like**
I would love to see a solution that could be a win/win for us users and for the Buddy Boss organization by utilizing a good amount of the framework and UI that is already developed for other parts of the current Buddy Boss Platform and further optimized or styled by the Buddy Boss theme. The solution could be outlined as follows:

**BuddyBoss Platform Business Pages**

Add new component Business Pages(Fan Pages, etc.) to enable or disable from BuddyBoss -> Components

Business Pages could follow and use the same framework as Groups as this will allow multiple site members to be invited to be a Page “admin”.

Allow user to create their pages slug and label. For this outline I will use the slug and label “businesses” or “business page”. But I could see some wanting to have the slug “suppliers” or “fan-page”, etc. 

Admin roles to be Administrator (top level), Moderator (mid level), Editor (low level).

Create a Business Page to work in the same process as Create a Group with steps laid out to create a page. 

Step 1 - Details - This section needs to have a little bit more functionality than Groups and also would need some front end styling for the data output on the Business Page Details Section. The functionality would be very similar to the back office for BuddyBoss->Profiles->Profile Fields, Types and Search but would be for Business Page Fields, Page Types and Search with the ability to add/omit fields for the Business Page Details Section.

Step 2 - Privacy - We could omit this section since all business page profiles would be visible. Instead we could add a section to define page role abilities. 

Step 3 - Discussions - We could omit this section as it’s irrelevant to a business page.

Step 4 - Profile Photo or "Company Logo"

Step 5 - Cover Photo

Step 6 - Photo Gallery - ability to upload some images into the Business Page’s gallery to start off with. 

Step 7 - Invitations - these invitations would be to site members that are invited to be a page “admin” by the main Administrator. 

___________

Some notes:

1. Location should use location autocomplete so we can include a more precise location search at the top of the Business Pages Archive page. I think this could be a required purchase by the end user if they want to have the ability to enable a nice looking location search on the archive page. 
2. When a site member posts an update, they will now need the ability to use the drop down to pick where they are posting their update and select from the options 1. Post in Profile 2. Post in Group -> Type Group Name Here 3. Post in Page -> Type in Page Name Here
3. Would be awesome to incorporate a map function in the future to map these businesses (possibly a buddy boss paid for add on)
4. In the Business Page settings, the site owner or community owner should have the option to either allow or disallow the ability for the Business Page's post updates to hit the main activity feed. This is a great monetization vertical and another possible paid for add-on where buddyboss could add a lot of value while also earning from the add-on. An add-on could provide a pay wall to allow the business to pay to have their post hit the main activity feed for distribution to all users. 

**Describe alternatives you've considered**
I have only considered hiring the development of this feature on my own but I know there are many buddyboss platform users that would love to see a "Business Pages" component based on the feedback I'm getting from reaching out to others that I see commenting in the forums, etc. 

**Support ticket links**
I have not submitted this information to the ticketing platform.

**Comment by bryanr18lowe** [comment]
@eisenwasser Thanks so much for having a look at this new feature and considering it for the road map.

**Comment by bryanr18lowe** [comment]
More notes: 

-We would have a "my pages" tab where we would get a curated list of business pages that we administrate. 
-In the archive page, the business pages in either card or list format wouldn't have "join this business page" or Private/Public, etc.

**Comment by bryanr18lowe** [comment]
Another note: It makes sense to have another Admin Role for simply "Page Member" or "Page Affiliate" where the site member is related to the page but does not have any editing or posting permissions. This would be the lowest level page role. I'm thinking about how this is the most inclusive component for all and many niche professional networks would need the ability to list people as being related to or an employee of the business page but wouldn't want all of their employees posting as the page at will.

**Comment by bryanr18lowe** [comment]
Note Regarding Posting: When posting an update and choosing "Post in Page", it will need to bridge functionality over to "Post AS Page" so the business is posting into their activity feed and not an individual site member is posting for the page from a front end display prospective.

**Comment by eisenwasser** [comment]
Thanks for the super detailed scope!

We have seen a number of requests for business pages in the past. We will consider all of this. It's not on our official roadmap as the roadmap is just through Q3 of this year. But this (or some version of this) will likely be added into the roadmap later on.

**Comment by bryanr18lowe** [comment]
Thanks @eisenwasser I appreciate your consideration!

**Comment by tonymeltone** [comment]
I like the idea of the Business Page construct outlined.

In our case, our members are athletes and connect with college coaches (also members) and Colleges (Groups).

I like the idea of fielded data.  NOTE:  It should allow searching and filtering for businesses on that fielded data.   Similar to a profile search, but for a Business (or Organization) search.

If this is implemented, I like that I can preserve the use of Groups for its original purpose.  Right now, I am using Groups as my Organization (or Business) object.  There are several shortcomings of using Groups this way (no fielded data or search is a big one).  In addition, it requires fairly extensive translation.

Members should be able to follow a Business (or Organization) and that Business's updates appear in the feed.  Members should also be able to message a Business.

I would imagine that management rights of a new Business object can work similarly to groups.  You can have administrators and editors.

**Comment by tonymeltone** [comment]
Oh..one other thing... It would be nice if you could export "Groups" so you could import them as "Businesses".  It would be ULTRA-SUPER-MEGA nice if you could check a box on a group and re-classify them as a "Business" (with all the connections being migrated).

**Comment by zachkinsey** [comment]
I also want business pages. :D

**Comment by eisenwasser** [comment]
@tonymeltone 

`There are several shortcomings of using Groups this way (no fielded data or search is a big one)`

This is something I have wanted to add to groups since the start. Fielded data, and an advanced group search form. It's a very big project, but I do think we will loop back to this eventually.

Maybe we do Business Pages, or maybe we just make groups more extendable. We can make it easier to have different group directories based on group type. I could imagine if groups had enough options it could be possible to easily repurpose some group types as businesses. 

Although - I have had my own ideas for business pages that somewhat invalidates using groups for them. I think it would be cool to post content around the network with the business itself as the author of that content. We'll come back to this eventually and figure out a proper scope.

**Comment by bryanr18lowe** [comment]
@eisenwasser @tonymeltone I completely agree that we'd need to still keep groups intact and we'd want to be able to use groups how they are right now (the addition of fielded data and an advanced search would be amazing). I was trying to find the easiest way to describe a possible model to follow that would get us about 80% and then we could go from there.

**Comment by tonymeltone** [comment]
Unfortunately, I am pretty needy for this functionality now.  So, I am going to work with a developer to customize.  I am going to approach this by adding a new profile type and profile group and create the colleges as Member profiles rather than groups.  Unfortunately, the groups functionality is too limiting (no fields, no search)

 We will create a new member directory page that only shows the listing of members from the “College” profile group.   The rows retrieved will display the specific data from the College profile group fields.  In addition, we will create a new filter widget that allows the searching of the specific fields I want to filter for this profile group.  

There are a couple of downsides.  One is the first and last name construct.  We will get around this by putting the college name in the first name field and their division in the last name field.  The other is email address in the event if a person’s email is on the college profile and then they want to become a real member.  We will have to update manually if that occurs.

**Comment by eisenwasser** [comment]
@tonymeltone Sounds like a solid plan. Don't wait for us on this if you need it now, nobody here will be working on this task for some time.

**Comment by eisenwasser** [comment]
@bryanr18lowe Thanks for the feedback. Yes, fielded groups with group search would be really nice, even ignoring business pages. It just makes groups so much more flexible. I think we will get to it eventually, it's just a large project to create all of the field types. The way profile fields are doesn't make them portable over to groups, we need to recreate all of that from scratch and/or restructure things in a big way.

**Comment by chrishthompson** [comment]
@eisenwasser I know you've thought about this and understand the code way more than I have.  Here are a few of my quick thoughts for what it's worth...putting it here because it seems like the most relevant place.

Extend Groups:
- In general, I'm a fan of the idea of extending groups so they can be more, and more flexible.  Like CPT's can be totally different things than posts, I'd love it if Custom Group Types could be defined with their own slugs, etc.  I've just started building, but I turned "groups" into "projects" throughout the platform and theme using Loco Translate.  Works great.  But it would obviously be better if we had full CGT functionality with slugs and such like we have with custom post types.
- Definitely would love to have the ability to extend a custom group type with custom fields.
- Would love to have the ability to enable/disable functional chunks of of a CGT just like we can when we make a new post type so we can turn off bits that aren't necessary for the "project" or "team" or "department" or "client" or....whatever.

Business pages?
- I may be missing something, but it seems better to extend groups instead of creating a whole new thing?
- Maybe the ideas of what a group could be or what a business page could be should be combined into a totally new type of module that fully replaces the buddypress "group" with something that works better for both purposes and enables multiple custom types to be instantiated (or whatever the right word is in PHP land).

Feel free to totally reject all this of course.  :-)

**Comment by bryanr18lowe** [comment]
@eisenwasser I'm very close to closing an investment round and need to talk to you about the estimated cost to implement the business pages feature for me as a custom developed featured. What is the best way to send this information to you? I need to expand a little upon what I laid out above to outline our needs now that we know a bit more about our actual needs in a live environment.

**Comment by bryanr18lowe** [comment]
@eisenwasser This could be a win/win for both of us as I can off-set your costs to develop this feature and I'm ok with it making it into future versions of the platform.. We would just need to streamline the development to ensure we can get this done in a timely fashion.

**Comment by eisenwasser** [comment]
@bryanr18lowe 

We are not able to implement this in the product itself in a streamlined timeframe. Right now we have a lot on our roadmap that people are waiting for, and all of it will take time to implement. It is not an issue of cost as much as just that it takes considerable time to properly scope, develop, test and release big features. We are not planning to get into business pages until some time later in 2021 most likely.

**Comment by bryanr18lowe** [comment]
@eisenwasser thanks for the insight. Is it not possible to hire your agency to develop this for me outside of the standard road map then?

**Comment by eisenwasser** [comment]
@bryanr18lowe 

We can consider this for a custom project. Please send me an email michael@buddyboss.com

**Comment by eisenwasser** [comment]
@bryanr18lowe I am assuming you received an email notification with my last response. Please send me an email. I am deleting the previous post so my email is not exposed publicly. Thanks.

**Comment by TokumeiJG** [comment]
Just want to add that I am also very interested in this since I run a site focused on travel and there are many guides/businesses that would like official pages.

**Comment by teddyskokos** [comment]
I am very interested in this feature too. I expect to have a very important use and need for it sometime in 2021.

**Comment by bryanr18lowe** [comment]
@eisenwasser Hi Mike, I hope all is well and Happy New Year! Per your suggestion in your email, what is the best way to schedule a time for a follow up call to discuss this?

**Comment by stanner202** [comment]
Just adding here that this is a pretty high priority for us. We use Geodirectory for now but would prefer more social functions like having "post as" functionality.

**Comment by DomDomonom** [comment]
Yeah the lack of this feature being on the roadmap is making me hesitant to pivot to BuddyBoss

**Comment by marienel21** [comment]
Hi @stanner202,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team

**Comment by StinkyBytes** [comment]
Can't find these features anywhere in the latest release.

![Screenshot 2021-06-30 at 20-19-45 buddyboss buddyboss-platform](https://user-images.githubusercontent.com/9968067/123982715-e4d50700-d9e0-11eb-90d7-69c06b5c242f.png)

**Comment by seventyone-digital** [comment]
Caught the post above re: closing this post to focus on tasks ready for development but ... anyone know if Business Pages remain in the pipeline? Realize this is a big 'ask' feature to implement but also a huge step forward for communities that are not education driven for monetization. Business Pages (LinkedIn / Facebook) are table stakes for a community that connects users with businesses. We have Job Board integration (at MVP stage) and businesses want to be able to access the additional features (private messaging / groups / docs / search and filter / etc). I think that being able to leverage the robust capabilities (and now native app option) of BB is a difference maker with regards to monetizing specific communities into scalable eco-systems. The issue with development outside of the platform unfortunately becomes compatibility with  future updates etc. Even a way to display a specific profile / role differently on the frontside would help. Swap First Name and Last Name fields for Organization type idea - so templates (conditional on profile) could work? I'll submit a request into the roadmap as well but if anyone has pursued this with any luck please let me know - perhaps there's a way to collaborate

**Comment by TokumeiJG** [comment]
@seventyone-digital maybe submit it on the roadmap?
https://roadmap.buddyboss.com/tabs/2-planned/submit-idea

**Comment by bryanr18lowe** [comment]
@seventyone-digital I am open to collaborate or share cost of development of this feature if the right situation (developer) presented itself. I am interviewing developers right now as I had contracted someone who completely disappeared during the heat of the pandemic so I'm praying he is OK but... I still need business pages and need them to function flawlessly as my revenue model depends on them. What is the best of touching base with you to discuss?

**Comment by seventyone-digital** [comment]
just reached out to a developer who has a Beta type version - more inline with WP-JobManager and job boards - we're going to purchase a few of his other plugins and I'll see if perhaps he has any insight / bandwidth - keep you in the loop. We should touch base for sure --> email should be public

**Comment by greg-182** [comment]
Hei!

So is there a BuddyBoss business page plugin or something good available? The best I have found is this:

https://wbcomdesigns.com/downloads/buddypress-business-profile/
