### ISSUE TITLE
Slow Page Loading for Forum-Discussion

### ISSUE THREAD

**Issue by jessa29** [buddyboss/buddyboss-platform#911]
**Is your feature request related to a problem? Please describe.**
Yes, when too many replies/comments are in a discussion, the page loads very slow. System takes time to load all comments. The platform works fine if its just 20 to 50 comments however, if you have 100-300 comments, loading it takes a while regardless if you have met the Server criteria or have added CDN, optimize your site. Nothing works with it and its just the same. This has been a known issue particularly with Forum-discussion page.

**Describe the solution you'd like**
To have the Forum-discussion page load faster regardless of how many comments/replies there is. 

**Describe alternatives you've considered**
We can try to use Skeleton Loader for this as this has been tested by one client.

**Support ticket links**
https://secure.helpscout.net/conversation/1155981610/71967?folderId=3827369

**Comment by marienel21** [comment]
Hi @jessa29,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
