### ISSUE TITLE
Notifications for different groups "request group membership"

### ISSUE THREAD

**Issue by jessa29** [buddyboss/buddyboss-platform#912]
**Is your feature request related to a problem? Please describe.**
This was an enhancement request for the notification function. When members are sending request to join different groups the admin is notified and when clicking 1 of those request the notification icon no longer shows the rest of the request and admin can only see it once they get into the Notification Page where it will show as Unread. Client wants this function adjusted same like with Facebook where the notification stays in when you click the icon. This request was to help those users who are not familiar with navigating the site. Added the screenshots below:

![image](https://user-images.githubusercontent.com/65430651/82145136-4daffd00-987b-11ea-8ba0-3b6ecf1d00c1.png)
![image](https://user-images.githubusercontent.com/65430651/82145163-7afcab00-987b-11ea-9f2e-b169496296b5.png)
![image](https://user-images.githubusercontent.com/65430651/82145166-818b2280-987b-11ea-8019-eb5d9e9ec4cb.png)
![image](https://user-images.githubusercontent.com/65430651/82145168-87810380-987b-11ea-8127-b189afdcc8b9.png)
![image](https://user-images.githubusercontent.com/65430651/82145172-8d76e480-987b-11ea-852d-ea56e6e7250e.png)

**Describe the solution you'd like**
Adjust the notification function to keep the request remain in when user clicks the notification icon.

**Describe alternatives you've considered**
Adv to check directly in the Notification page instead of clicking 1 of those request. 

**Support ticket links**
https://secure.helpscout.net/conversation/1162638003/73131?folderId=3827369

**Comment by marienel21** [comment]
Hi @jessa29,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
