### ISSUE TITLE
Forums -links-return-404-errors

### ISSUE THREAD

**Issue by jessa29** [buddyboss/buddyboss-platform#913]
**Is your feature request related to a problem? Please describe.**
This is a feature enhancement request, client wants to have us have a permanent fix with pages showing as 404 error. https://www.loom.com/share/2ebcd738561241b98605f46c29610116

**Describe the solution you'd like**
Does not like the work-around with permalinks, rather was hoping we can find a fix solution for this issue and would be added to our future enhancement of our product.

**Describe alternatives you've considered**
To fix this navigate to Dashboard -> Settings -> Permalinks. Try selecting the ‘Post Name’ option and then click Save Changes. In most cases this will resolve your link issues. Here is a video tutorial for these steps:
https://www.buddyboss.com/resources/docs/troubleshooting/menu-links-return-404-errors/

**Support ticket links**
https://secure.helpscout.net/conversation/1160838194/72823/

**Comment by marienel21** [comment]
Hi @jessa29,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
