### ISSUE TITLE
Bigbluebutton integration

### ISSUE THREAD

**Issue by mailalaki** [buddyboss/buddyboss-platform#914]
Hi, please add Bigbluebutton integration too. its very useful
https://wordpress.org/plugins/bigbluebutton/
http://docs.bigbluebutton.org/dev/api.html

**Comment by marienel21** [comment]
Hi @mailalaki ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
