### ISSUE TITLE
New Enhancement Suggestion: profile hovercards

### ISSUE THREAD

**Issue by haroldkip** [buddyboss/buddyboss-platform#915]
Profile hovercards could be a nice feature. Something like https://community.spiceworks.com does and is illustrated below. 

![image](https://user-images.githubusercontent.com/65546974/82252762-e31cc100-994f-11ea-87f9-33c18cb31816.png)

**Comment by marienel21** [comment]
Hi @haroldkip,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
