### ISSUE TITLE
Better Buddydev Profile Visibility Manager Integration

### ISSUE THREAD

**Issue by zachkinsey** [buddyboss/buddyboss-platform#916]
**Is your feature request related to a problem? Please describe.**
Having two profile privacy pages doesn't really make sense.

**Describe the solution you'd like**
Hopefully I put this enhancement under the right tag... heh. Currently, the buddydev plugin ( https://buddydev.com/plugins/bp-profile-visibility-manager/ ) creates a new privacy page called 'Profile Privacy'. Ideally, it would be integrated into the 'Privacy' page that comes with BuddyBoss. Additionally, the radio buttons would be styled with the BuddyBoss styles.

**Comment by marienel21** [comment]
Hi @zachkinsey,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
