### ISSUE TITLE
Cannot post blog links into Activity or Groups

### ISSUE THREAD

**Issue by bolorino** [buddyboss/buddyboss-platform#947]
**Describe the bug**
Trying to publish a message in activity or into a group containing a link to a blog post in the same site/domain throws an error in console.
The preview isn't generated and the message cannot be published. 

The activity messages about blog post updates don't include a preview. 
The preview was working on previous version, 1.4.5. 

**To Reproduce**
Insert a link to a blog post on the same site in a message in Activity or in a group. 

**Expected behavior**
A preview is shown when the link is added. 
After pressing "Publish" the message is published.

**Result**
There is no preview. A "TypeError" is thrown in console. 
After pressing "Publish" nothing happens. Another "TypeError" is thrown. 

**Support ticket links**
BuddyBoss ticket: #75350

[publishing-message-error.log](https://github.com/buddyboss/buddyboss-platform/files/4702425/publishing-message-error.log)
[pasting-link-error.log](https://github.com/buddyboss/buddyboss-platform/files/4702427/pasting-link-error.log)

**Comment by eisenwasser** [comment]
@bolorino 

Thanks for posting this. I cannot replicate this however.

In my localhost I am able to publish the activity post just fine. I just tested in our demo, if I paste a blog URL from the demo site into activity feed it generates the preview and publishes just fine.

Preview - https://prnt.sc/sq8em5
Published - https://prnt.sc/sq8ew2

So I don't think the issue is specifically related to blog posts from the same domain. It is obviously a real issue on your site but probably something else is happening. The blog previews are using WP default embeds, not our own embed, so maybe that WP embeds are disabled on your site somehow. Need to check whats happening on your site.

**Comment by eisenwasser** [comment]
To clarify, WordPress has its own embeds for certain things. Like blog posts, Twitter, Youtube embeds, stuff like that which they specifically support. All other links are using our custom embed script. The blog post should be picking up the WP embed, for some reason it's failing on your site.

**Comment by bolorino** [comment]
Thank you @eisenwasser 
Will investigate further.

**Comment by eisenwasser** [comment]
@bolorino Ok thanks
