### ISSUE TITLE
Protect YouTube video in LearnDash courses from download

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#949]
**Is your feature request related to a problem? Please describe.**
Could you protect youtube videos in LearnDash courses from download? This is necessary to protect courses from piracy.
User should not be able to go to youtube.com/watch?v=VIDEO_ID
User does not have to understand that the video is uploaded to youtube.com

**Describe the solution you'd like**
You may replace default youtube player to custom player, which will hide youtube links, annotations, brand youtube logo, end screen and context menu (right click).
Or you can hide this elements with using CSS and JS code. 

**Describe alternatives you've considered**
For example I have seen similar solution in LMS in https://justclick.io service.

**Comment by AiratHalitov** [comment]
Maybe you will change video-player parameters 

Docs: 
https://developers.google.com/youtube/player_parameters
https://support.google.com/youtube/answer/171780?hl=en

Examples: 
https://youtubevideoembed.com/
https://youtubeembedcode.com/en/

**Comment by eisenwasser** [comment]
@AiratHalitov Thanks for the suggestion.

This would require changing how LearnDash works which is beyond what we are trying to do. Our top priority with LearnDash is making sure everything in LearnDash itself works as they intend for it to, because customers are using it in so many ways and we don't want to break anything. This feature request is better directed at LearnDash itself as this is really a feature that makes sense in their core product. 

I would suggest trying Vimeo or AWS for hosting videos. They can let you restrict the videos to only your domain so they cannot be played outside of it and cannot be downloaded.

**Comment by AiratHalitov** [comment]
Could you give a example how can I use AWS+ LearnDash?
Vimeo is not a good solution. They can delete your account and all videos in any time.

**Comment by eisenwasser** [comment]
@AiratHalitov For AWS you need to create an S3 bucket to store your videos in and then you can upload videos to that bucket. Or use a plugin like https://deliciousbrains.com/wp-offload-media/

Then you can restrict access for the videos (to the S3 bucket) to your own domain following a tutorial like https://help.optimizepress.com/article/656-setup-your-amazon-s3-bucket-permissions-to-protect-videos-you-use-in-the-video-player-element

Keep in mind AWS is not user friendly in the same way as Youtube or Vimeo. It's much more technical and complicated to set this type of stuff up at AWS as it's for developers and server admins primarily.

**Comment by AiratHalitov** [comment]
@eisenwasser 
Thanks for the instruction!

Can’t I use my VPS to download videos and protect them from downloading?
