### ISSUE TITLE
Members Profile Types slugs

### ISSUE THREAD

**Issue by KaloyanNaumov** [buddyboss/buddyboss-platform#960]
**Is your feature request related to a problem? Please describe.**
The Profile type URLs are currently a set of GET parameters - ?post_type=bp-member-type&p=35

**Describe the solution you'd like**
I think a slug would be welcome either as root-level slug, or under the users directory "/members/" "/users/", whatever is configured. As in the video example, the two slugs would be - "teachers", students. 

e.g. /users/teachers, /users/students ... 

When users hit the URL, they will see the list of users attributed with the profile.

**Describe alternatives you've considered**
SEO tools can probably do the trick, but this is good contender for a built-in platform feature, IMO.

**Support ticket links**
Haven't bothered support with it. Thanks for looking into it.

**Comment by eisenwasser** [comment]
It's a cool idea, we'll see if it is possible. Thanks!

**Comment by marienel21** [comment]
Hi @KaloyanNaumov ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
