### ISSUE TITLE
Event featured image is not being included in the activity

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#972]
**Describe the bug**
When using **The Event Calendar: Community Events** addon to submit an event, the featured image uploaded is not being included on the activity feed.

**To Reproduce**
1. Install The Event Calendar plugin and the Community Event addon.
2. In BuddyBoss > Settings > Activity > Custom Post Type, enable Events
3. In Events > Settings > Community > Under general, set "Default status for submitted events" to **Published**
4. Now go to the event submit form, **/events/community/add**
5. Submit an event and make sure to upload a featured image
6. Check the sitewide activity and notice that the event activity entry does not include the featured image, unlike when uploaded through the backend the featured image is showing on the activity.

**Screenrecording**
When using the backend to add event: 
https://drive.google.com/file/d/16oAsQ3rr_mliN4r10ERS6XjBc01ycj-V/view
![backend](https://user-images.githubusercontent.com/58522498/83578854-54708c80-a56a-11ea-8b35-c93ca2615ef7.png)

When using the frontend event form:
https://drive.google.com/file/d/161LKKe8CWf5MFdEI8-gaz6zNzznP1Ywo/view
![frontend](https://user-images.githubusercontent.com/58522498/83578847-50446f00-a56a-11ea-9e87-00530c28854d.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1177823688/75346?folderId=3709081

**Comment by marienel21** [comment]
This bug is no longer observable in the current version of the product. 
Steps done: 
1. Using the Community Events addon plugin, created an event in the frontend 
2. Added feature Image. This image displays in activity  
![image](https://user-images.githubusercontent.com/77659570/125465957-b1d84261-6be8-4964-85da-8c4d67e53816.png) 
![image](https://user-images.githubusercontent.com/77659570/125466052-0aea9a54-942e-4735-998a-cd560e90f522.png)
