### ISSUE TITLE
Ajax search suggestions close upon page or mouse scroll

### ISSUE THREAD

**Issue by StinkyBytes** [buddyboss/buddyboss-platform#975]
**Is your feature request related to a problem? Please describe.**
Ajax search suggestions close  automatically when the page or mouse scrolls. This may be confusing or frustrating for some users. 

**Describe the solution you'd like**
An option should be given if the suggestions should close upon page scroll, via click on empty area on page or via click on the close button in search input field.

_Original code at /wp-content/plugins/buddyboss-platform/bp-templates/bp-nouveau/js/buddypress-search.js_
```
/**
 * Close the suggestion box when the page scrolls
*/
window.addEventListener( 'scroll', function () {
	var arrayLength = autoCompleteObjects.length;
	for ( var i = 0; i < arrayLength; i ++ ) {
		autoCompleteObjects[i].autocomplete( 'close' );
	}
} );
```
The above code has an anonymous function which can be changed to a named function allowing us to use **removeEventListener** to remove the close behavior on scroll. Even better if a simple switch could be added to BuddyBoss Platform settings.

**Comment by marienel21** [comment]
Hi @StinkyBytes,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
