### ISSUE TITLE
Cannot add options in the dropdown field beyond 242 when it allows adding 250 options. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#988]
**Describe the bug**
Cannot add options in the dropdown field beyond 242 when it allows adding 250 options. 

**To Reproduce**
1. Go to BuddyBoss > Profiles
2. Create a dropdown field
3. Add options, it won't allow adding an option beyond 242

**Expected behavior**
It should work up to 250 options as mentioned.

**Screenshots**
-

**Support ticket links**
- https://secure.helpscout.net/conversation/1176776496/75199?folderId=3709075

**Comment by rmmehta** [comment]
I am not able to replicate the issue. I have flowed reproduce the issue but i am able to add the option beyond 250 as well.

You can see the this video for the same : [https://www.loom.com/share/0055ac5fc8da44fdb5346372df54110c ](https://www.loom.com/share/0055ac5fc8da44fdb5346372df54110c )

This issue is  not there in the platform SO,  I have close this issue.

Thanks,
