### ISSUE TITLE
Allow members to tag friends/contacts in media uploads

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#997]
Allow members to tag friends/contacts in media uploads.

![image](https://user-images.githubusercontent.com/4050715/84009566-e58d9c00-a98c-11ea-8390-3758a9aa761d.png)

**Describe alternatives you've considered**
This solution is working in your [BuddyBoss Media](https://www.buddyboss.com/product/buddyboss-media/) plugin.

- buddyboss-platform 1.4.1

**Comment by marienel21** [comment]
Hi @AiratHalitov,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
